### ISSUE TITLE
Add DiscardableResult to array functions

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#100]
Currently the functions for appending and pushBack return a bool. This return value can be made into a discardable result so it's not giving a warning of an un-used return value.

Example is PackedStringArray but I'm sure there are other collection types.
<img width="749" alt="Screenshot 2023-07-28 at 11 18 46 AM" src="https://github.com/migueldeicaza/SwiftGodot/assets/1486399/432d9640-b539-44f6-95c3-9b5a8f21d472">

**Comment by migueldeicaza** [comment]
I think this is useful, and I think that we should have a file describing these "edits" to the API.

I was considering doing that for the nullability annotations as well, so might as well do it in the same place.

**Comment by migueldeicaza** [comment]
Done with a built-in list, rather than a general purpose Json file.
