### ISSUE TITLE
You don’t have permission to save the file “Nil.swift” in the folder “generated-builtin"

### ISSUE THREAD

**Issue by xiaobeiswift** [migueldeicaza/SwiftGodot#111]
Generator/Printer.swift:57: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “Nil.swift” in the folder “generated-builtin”." UserInfo={NSURL=file:///Volumes/game/godot/RPG/build/plugins/outputs/swiftgodot/SwiftGodot/CodeGeneratorPlugin/GeneratedSources/generated-builtin//Nil.swift, NSUserStringVariant=Folder, NSUnderlyingError=0x60000389da40 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}

m2,xcode 15

**Comment by migueldeicaza** [comment]
Maybe you didn’t trust the build
