### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftGodot#117]
```
    private func testMeshInstanceLeak() {
        GD.print("going")
        self.displayed?.queueFree()
        
        let cylinder = CylinderMesh()
        cylinder.topRadius = 10
        cylinder.bottomRadius = 9
        cylinder.height = 40
        cylinder.radialSegments = 200
        
        let surfaceTool = SurfaceTool()
        surfaceTool.begin(primitive: Mesh.PrimitiveType.primitiveTriangles)
        surfaceTool.appendFrom(existing: cylinder, surface: 0, transform: Transform3D())
        surfaceTool.generateNormals()
        let array = surfaceTool.commit(existing: nil)
        surfaceTool.clear()

        let meshInstance = MeshInstance3D()
        meshInstance.mesh = array
        self.addChild(node: meshInstance)
        self.displayed = meshInstance
    }
```

So this code seems to just leak CylinderMesh and MeshInstance3D.

<img width="818" alt="Screenshot 2023-09-20 at 8 52 48 AM" src="https://github.com/migueldeicaza/SwiftGodot/assets/1486399/7bcde636-2164-4b52-a275-a141dbc58ff6">

_Originally posted by @nvanfleet in https://github.com/migueldeicaza/SwiftGodot/issues/102#issuecomment-1727997503_

**Comment by tishin** [comment]
It's much simpler, this example is enough to leak `MeshInstance3D` wrapper on the Swift side:
```
@Godot
class CustomNode: Node {    
    override func _ready() {
        let mesh = MeshInstance3D()
        mesh.queueFree()
    }
}
```

The underlying c++ `MeshInstance3D::~MeshInstance3D()` deallocation happens, `frameworkTypeBindingFree` gets called and cleans up `liveFrameworkObjects` dictionary, but the Swift object remains retained.
So it looks like every "framework" object allocated in Swift ends up leaked. Doesn't happen with custom "subtyped" objects.
