### ISSUE TITLE
Property wrapper for getNode?

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#118]
I've been experimenting a little with this project and wanted to make dealing with nodes a bit easier. 

I made "NodePath" property wrapper that calls into a generic version of the `getNode` method, so you can do this:

```swift
class Circle: Area2D {
    @NodePath("Pivot/OrbitPosition")
    var orbitPosition: Marker2D

    @NodePath("Sprite2D")
    var sprite: Sprite2D

    @NodePath("CollisionShape2D")
    var collisionShape: CollisionShape2D

    @NodePath("Pivot")
    var pivot: Node2D
}
```

I spent a while considering the use of marcos to generate the node properties directly from a parsed `.tscn` file, but it seems that Macros are forbidden from reading from the filesystem. I guess code-gen might be an option? 

Anyway, if you like the property wrapper idea, I can submit a PR for that at least.

**Comment by nvanfleet** [comment]
How do you have this non-optionally? 

(I also am not sure but maybe I met you for an iOS conference in Montreal)

**Comment by PadraigK** [comment]
> How do you have this non-optionally? I mostly use optionality and some generic casting for my purposes.

In my code right now, I'm just returning an empty `T()` when the node isn't found and emitting a log message. `fatalError()` has overly-severe consequences, including taking down the godot editor. 

So far, as long as I don't have typos, they've never been nil when I reach for them... but I'm still finding my way around the lifecycle these objects, so I have no idea if some kind of force-unwrapping can be practical yet.

**Comment by PadraigK** [comment]
I guess I don't really need to be mysterious about it, here's the code that I have so far:

```swift
extension Node {
    func getNode<T: Node>(path: String) -> T {
        guard let node = getNodeOrNull(path: .init(from: path)) as? T else {
            GD.print("Could not find node \(path)")
            return T()
        }
        return node
    }
}

@propertyWrapper
struct NodePath<T: Node> {
    private let path: String

    init(_ path: String) {
        self.path = path
    }

    @available(*, unavailable, message: "@NodePath can only be applied to classes")
    var wrappedValue: T {
        get { fatalError() }
        set { fatalError() }
    }

    static subscript<EnclosingSelf>(
        _enclosingInstance instance: EnclosingSelf,
        wrapped _: ReferenceWritableKeyPath<EnclosingSelf, T>,
        storage storageKeyPath: ReferenceWritableKeyPath<EnclosingSelf, NodePath<T>>
    ) -> T {
        get {
            let wrapper = instance[keyPath: storageKeyPath]
            guard let instance = instance as? Node else {
                fatalError("NodeGetter must be used inside a class that has a getNode method.")
            }
            return instance.getNode(path: wrapper.path)
        }
        set {
            fatalError("NodeGetter is read-only.")
        }
    }
}
```

**Comment by nvanfleet** [comment]
I don't personally like the idea of instantiating a dummy T() in the failure case. IMO I'd prefer to just use optionality but otherwise that's mostly what I do. The property wrapper is pretty cool though. I have a bunch of conveniences but haven't been exactly sure about how to contribute them though

**Comment by PadraigK** [comment]
Ahhh I just discovered that `BindNode` already exists and already does exactly this.

**Comment by migueldeicaza** [comment]
I do like the idea of having some sort of automatically generated bindings from a scene.

Perhaps we could wire this up in a SwiftPM task

**Comment by migueldeicaza** [comment]
I will close this issue for now, unless there is something else we want.
