### ISSUE TITLE
Can't `await` signals outside a concurrency context.

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#124]
The [docs](https://github.com/migueldeicaza/SwiftGodot/blob/20d7b5534e94d88f2944a69556975b3b6f2ce9e9/Sources/SwiftGodot/SwiftGodot.docc/Signals.md?plain=1#L77) tell us we can `await` the `emitted` property of a signal, but this doesn't compile as is — it must be at a minimum wrapped in a Task. 

If we do wrap it in a task, as follows:

```swift
func implode() {
    let player = … // gets an animationPlayerNode
    if !player.isPlaying() {
        player.play(name: "implode")
    }

    let signal = player.ready

    Task {
        await signal.emitted
        callDeferred(method: "queue_free")
    }
}
```

Godot complains with:

> E 0:00:02:0214   connect: Caller thread can't call this function in this node (/root/Main/Circle/AnimationPlayer). Use call_deferred() or call_thread_group() instead.
  <C++ Error>    Condition "!is_accessible_from_caller_thread()" is true. Returning: (ERR_INVALID_PARAMETER)
  <C++ Source>   scene/main/node.cpp:3605 @ connect()

**Comment by migueldeicaza** [comment]
Thanks for pointing this out, I will update the docs.

Could you try making the function async, and then make sure that the method you call is flagged with @MainActor?

```
func implode () async {
...

await signal.emitted
callThing ()
}

@MainActor
func callThing () {
callDeferred ()
}
```

**Comment by PadraigK** [comment]
Thanks, I was able to get it working like this:

```swift
func implode() {
    jumper = nil
    if !animationPlayer.isPlaying() {
        animationPlayer.play(name: "implode")
    }

    Task { @MainActor in
        await animationPlayer.animationFinished
        queueFree()
    }
}
```

**Comment by migueldeicaza** [comment]
That would also work, yes.

Let me bring that to the documentation as it is a useful idiom.

**Comment by migueldeicaza** [comment]
Integrated into docs.
