### ISSUE TITLE
Unknown attribute 'Godot'

### ISSUE THREAD

**Issue by ismyhc** [migueldeicaza/SwiftGodot#131]
Hello!

Just now going through the tutorial and getting the following error when trying to build.

```
Unknown attribute 'Godot'
```
Ive set "Disable Library Validation". Also tried removing Hardened runtime all together.

![Screenshot 2023-09-26 at 7 00 54 PM](https://github.com/migueldeicaza/SwiftGodot/assets/840551/e81d9a18-ea3f-4528-8124-accfe8a9d1d7)

![Screenshot 2023-09-26 at 7 03 50 PM](https://github.com/migueldeicaza/SwiftGodot/assets/840551/fb221e85-4ca3-4c47-8783-68dc0301653d)

**Comment by alicerunsonfedora** [comment]
Do you have `SwiftGodotMacros` imported as well? `@Godot` is a macro that requires the `SwiftGodotMacros` library from the SwiftGodot package.

It looks like the tutorials currently don't show this, though a PR I do have open (#129) should resolve that.

**Comment by ismyhc** [comment]
> Do you have `SwiftGodotMacros` imported as well? `@Godot` is a macro that requires the `SwiftGodotMacros` library from the SwiftGodot package.
> 
> It looks like the tutorials currently don't show this, though a PR I do have open (#129) should resolve that.

Hmmm. Yeah I only added the SwiftGodotKit package. However, adding SwiftGodot Im now getting these errors.

![Screenshot 2023-09-26 at 7 29 05 PM](https://github.com/migueldeicaza/SwiftGodot/assets/840551/f75bec7d-04e7-4f31-a30c-1fc2f1229ff9)

I might just dig back in tomorrow morning. Im probably too burnt out today to properly get this working. lol. Could be something on my side and don't wanna waste your time :)

**Comment by alicerunsonfedora** [comment]
We'll have to see how you have your project set up. I suspect there's a bad configuration of some kind causing this issue.

**Comment by ismyhc** [comment]
> We'll have to see how you have your project set up. I suspect there's a bad configuration of some kind causing this issue.

Yeah this was simply new project, the add SwiftGodot branch main. 

I'll report back in the morning when my mind is fresh. 😅

**Comment by migueldeicaza** [comment]
Apologies, for now do two things:

1. Make sure that your dependencies in your package look like this:

```
            dependencies: ["SwiftGodot", .product (name: "SwiftGodotMacros", package: "SwiftGodot")],
```

2. Make sure that you import both SwiftGodot and SwiftGodotMacros

I attempted to bring the macro definitions into SwiftGodot so we did not need two imports, but did not succeed.   Might try again tomorrow.

**Comment by migueldeicaza** [comment]
I think the above should fix it, but I would still love to find a way of not requiring two libraries and two imports from people, will ask around.

**Comment by ismyhc** [comment]
> Apologies, for now do two things:
> 
> 1. Make sure that your dependencies in your package look like this:
> 
> ```
>             dependencies: ["SwiftGodot", .product (name: "SwiftGodotMacros", package: "SwiftGodot")],
> ```
> 
> 2. Make sure that you import both SwiftGodot and SwiftGodotMacros
> 
> I attempted to bring the macro definitions into SwiftGodot so we did not need two imports, but did not succeed. Might try again tomorrow.

I cannot figure it out for the life of me.

- Create new command line tool project
- Add SwiftGodot package
- Select only SwiftGodot and SwiftGodotMacros

![Screenshot 2023-09-27 at 9 03 12 AM](https://github.com/migueldeicaza/SwiftGodot/assets/840551/8aa9b2a0-628e-4cbe-a52f-ef05e1a3c5a8)
![Screenshot 2023-09-27 at 9 03 37 AM](https://github.com/migueldeicaza/SwiftGodot/assets/840551/f438ff47-bdff-4861-a686-c72bdb2bbca1)

If I remove SwiftGodotMacros it will build. However, If I then try to add the package SwiftGodotKit then I get this error when trying to add.

![Screenshot 2023-09-27 at 9 05 10 AM](https://github.com/migueldeicaza/SwiftGodot/assets/840551/0a2490a6-c6c5-424a-80ba-dc3c59c4256e)

Im using branch main for both.

Have you tried doing this on your side with a fresh new project?

Also, Im not sure how to find the package file to check if the dependencies are what you mentioned above.

**Comment by migueldeicaza** [comment]
Oh, I was using a fresh Swift package rather than a console app.

This means that the instructions were for SwiftPM and Package.swift, rather than for Xcode with an xcproject file.

**Comment by ismyhc** [comment]
> Oh, I was using a fresh Swift package rather than a console app.
> 
> 
> 
> This means that the instructions were for SwiftPM and Package.swift, rather than for Xcode with an xcproject file.

Ahhh. So instead I create new package, then import my package into a swift project?

Sorry I'm used to creating iOS apps via Xcode. 😅

**Comment by migueldeicaza** [comment]
I started a discussion on the Swift forums to find a simple process so folks don't trip into this:

https://forums.swift.org/t/macro-usage-experience/67554

**Comment by migueldeicaza** [comment]
You can still use Xcode, just use "New Package" instead of "New Project".

Here is a working sample:

https://tirania.org/tmp/sample-godot.tar.gz

**Comment by ismyhc** [comment]
> You can still use Xcode, just use "New Package" instead of "New Project".
> 
> Here is a working sample:
> 
> https://tirania.org/tmp/sample-godot.tar.gz

Sorry, I feel like Im wasting your time :) I tried the sample project but got the following errors.

![Screenshot 2023-09-27 at 2 08 15 PM](https://github.com/migueldeicaza/SwiftGodot/assets/840551/eb9c6787-81bd-4675-a3a7-b73f7c02c069)

Im sure, Im missing a step or something. I can wait until maybe there is a more clear step by step for dummies like me. lol

**Comment by migueldeicaza** [comment]
This is quite a puzzle, I am sorry about this frustrating experience.

I can confirm that I can build it from the command line just fine, but that Xcode fails to build it.

Apparently there are two parallel build systems for Swift, and this is tripping it.   I will report this issue.

**Comment by migueldeicaza** [comment]
Ok, I found a temporary work around.

This is driving me crazy.

1. If you are using Xcode, the dependencies need to be a single line:

```
            dependencies: ["SwiftGodot"],
```

2. If you are using SwiftPm you need to use:

```
            dependencies: ["SwiftGodot", .product (name: "SwiftGodotMacros", package: "SwiftGodot")],
```

Full version that works in Xcode:

```
// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "a",
    platforms: [
    .macOS(.v13)
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "a",
	    type: .dynamic,
            targets: ["a"]),
    ],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftGodot", branch: "main")
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "a",
            dependencies: ["SwiftGodot"],
            swiftSettings: [.unsafeFlags(["-suppress-warnings"])],
            linkerSettings: [.unsafeFlags(
                ["-Xlinker", "-undefined",
                 "-Xlinker", "dynamic_lookup"]
            )]
	),
	
    ]
)

```

**Comment by migueldeicaza** [comment]
I have asked for help:

https://forums.swift.org/t/macros-xcode-15-and-swiftpm-difference-of-opinions/67559

https://forums.swift.org/t/macro-usage-experience/67554

**Comment by migueldeicaza** [comment]
I believe this is now addressed.
