### ISSUE TITLE
Is there a good way to emit an failure message on preconditionFailure or fatalError?

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#132]
When we hit a `fatalError("couldn't find texture")` or `preconditionFailure("couldn't find texture")`, the godot extension crashes which is expected, but it would be very helpful if the failure message could be emitted somewhere. 

At the moment, the crash report doesn't include it. Logging with `GD.print` or `GD.pushError` doesn't seem to make it to the console. I suspect the extension is crashing before the logs are flushed.

During development, it's very useful to be able to crash when we hit an unexpected condition, so I'd love to hear if anyone has figured out a way to post a terminal message.

**Comment by alicerunsonfedora** [comment]
I wonder if it makes sense to utilize Swift logging to produce log messages that can display in both the terminal/Console.app and Godot. I'm uncertain if this will get around the crash before post, but I think it might be worth trying, say with at least as `print` message (not `GD.print`).

**Comment by PadraigK** [comment]
In case others are facing the issue of `fatalError` being too hard to track down, my current compromise for this has been to use `GD.pushError` to signal there's a problem and avoid `fatalError()` entirely by instead returning a default value. 

This is not great, because the game is now in an invalid state but as long as you act on the debugger errors that show up in the editor, it has worked better for me than trying to dig through crash reports or Console.app.

**Comment by migueldeicaza** [comment]
I am afraid there is no way of catching this error from Swift, going to close this, and the comments should be here for future folks that run into this problem.

**Comment by tim-blackbird** [comment]
One way of getting the messages is to run godot from a terminal. Any non-godot errors or print statements should be visible there.
Though, it would be nice to have stderr/stdout be visible in the editor directly.
