### ISSUE TITLE
Method already bound 'MainScene::newGame' error when using @Callable

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#140]
After fixing https://github.com/migueldeicaza/SwiftGodot/pull/139 I hit this error (though it is not the cause, I only mention it because the issue here won't reproduce until #139 is in)

When I register a method using the `@Callable` macro, I get a "Method already bound 'MainScene::newGame'" error in Godot's debug pane. This is because the class initializer is running on every instance. 

The docs recommend this as a class constructor idiom:
```swift
static var initClass: Void = {
    …
}()
```
which would work because the closure would run once in initialize the static variable... but the macro is expanding to:

```swift
static func _initClass () {
    …
}
```

which is just a static function whose body will run every time.

**Comment by migueldeicaza** [comment]
Oops, thanks for catching this.   This is a regression from my original implementation that used the property.

Will fix.

**Comment by migueldeicaza** [comment]
Fixed.

**Comment by PadraigK** [comment]
Thank you!
