### ISSUE TITLE
Idea to improve prefix removal on enum cases

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#144]
In enums like PropertyUsageFlags, the current prefix removal strategy of removing the enum name from each case doesn't work, because the cases are all prefixed with "PROPERTY_USAGE_" rather than "PROPERTY_USAGE_FLAGS". 

We could improve this by identifying the common prefix of all cases and removing that, instead of relying on the enum name matching the case prefix. 

Alternatively a simpler fix might be to special case enum names containing FLAGS, since they all seem to follow the pattern of dropping the "_FLAGS" part.

**Comment by PadraigK** [comment]
> Alternatively a simpler fix might be to special case enum names containing FLAGS, since they all seem to follow the pattern of dropping the "_FLAGS" part.

Actually this is not the case for `PipelineDynamicStateFlags` which has `dynamicStateLineWidth` and a number of other enums, so ignore this alternative.

**Comment by PadraigK** [comment]
Here's what I've got so far: https://gist.github.com/PadraigK/af78939c3e597635d6db5dc98e7b6c64

**Comment by migueldeicaza** [comment]
Closing by your PR
