### ISSUE TITLE
Need to copy `libSwiftGodotMacros.dylib` into `/bin` folder too

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#148]
Godot complains if I don't also copy this dylib into the /bin folder.

I suspect this is the cause: https://github.com/migueldeicaza/SwiftGodot/commit/f9f00d7136e4968c4315e41c174f138f8842135b

If we want to keep this dynamic, we should update the docs to instruct users to also copy this dylib.

**Comment by migueldeicaza** [comment]
Well, this is odd - because this should not be necessary at runtime at all.

What is the error that you get?

**Comment by tishin** [comment]
It is necessary to copy the `libSwiftGodotMacros.dylib` alongside extension's dylib, just like it was necessary to copy `libSwiftGodot.dylib` before macros were introduced. Tutorials cover that: https://github.com/migueldeicaza/SwiftGodot/blob/main/Sources/SwiftGodot/SwiftGodot.docc/Tutorials/Your%20First%20Extension.tutorial#L186
I think they should either both be static or both be dynamic. The way it worked before https://github.com/migueldeicaza/SwiftGodot/commit/f9f00d7136e4968c4315e41c174f138f8842135b: 
- when using plain `SwiftGodot`, its `libSwiftGodot.dylib` was linked dynamically (and had to be copied separately from driver's dylib)
- when using `SwiftGodotMacros`, the library (both `SwiftGodot` and `SwiftGodotMacros` targets) got embedded into driver's dylib (and the driver's dylib was enough to run the extension, contradicting tutorials)

Which I thought was confusing.

**Comment by tishin** [comment]
The way it works now:
- when using `SwiftGodot`, `libSwiftGodot.dylib` has to be placed alongside driver's dylib
- when using `SwiftGodotMacros`, `libSwiftGodotMacros.dylib` has to be placed alongside driver's dylib

**Comment by tishin** [comment]
Oh, I see the point of confusion now. You're probably using an extra dependency on `SwiftGodot` like so:
```
.target(
    name: "SimpleRunnerDriver",
    dependencies: [
        "SwiftGodot",
        .product(name: "SwiftGodotMacros", package: "SwiftGodot")
    ],
```
It makes `swift build` produce an extra `libSwiftGodot.dylib`, which is unnecessary since  `libSwiftGodotMacros.dylib` already contains `SwiftGodot` target due to `SwiftGodotMacros`'s static dependency on `SwiftGodot`. There's no need to copy `libSwiftGodot.dylib` to the `/bin` folder. And driver's package should be corrected to
```
.target(
    name: "SimpleRunnerDriver",
    dependencies: [
        .product(name: "SwiftGodotMacros", package: "SwiftGodot"),
    ],
```
Since the dependency on `SwiftGodot` is redundant.

**Comment by tishin** [comment]
To make it clear, I'll try to explain each configuration, I hope it makes sense

## 1. Before macros
Driver's package:
```
.target(name: "SimpleRunnerDriver",
    dependencies: [
        "SwiftGodot"
    ],
```
Output of `swift build`:
- libSimpleRunnerDriver.dylib, ~100Kb (SimpleRunnerDriver)
- libSwiftGodot.dylib, ~70 Mb (SwiftGodot)

Contents of `/bin` necessary to run the extension:
- libSimpleRunnerDriver.dylib
- libSwiftGodot.dylib

## 2. After macros (dynamic SwiftGodot, static SwiftGodotMacro), redundant dependency
Driver's package:
```
.target(name: "SimpleRunnerDriver",
    dependencies: [
        "SwiftGodot"
        .product(name: "SwiftGodotMacros", package: "SwiftGodot"),
    ],
```
Output of `swift build`:
- libSimpleRunnerDriver.dylib, ~70 Mb (SimpleRunnerDriver+SwiftGodotMacros+SwiftGodot)
- libSwiftGodot.dylib, ~70 Mb (SwiftGodot)

Contents of `/bin` necessary to run the extension:
- libSimpleRunnerDriver.dylib

## 3. After macros (dynamic SwiftGodot, static SwiftGodotMacro), correct dependency
Driver's package:
```
.target(name: "SimpleRunnerDriver",
    dependencies: [
        .product(name: "SwiftGodotMacros", package: "SwiftGodot"),
    ],
```
Output of `swift build`:
- libSimpleRunnerDriver.dylib, ~70 Mb (SimpleRunnerDriver+SwiftGodotMacros+SwiftGodot)

Contents of `/bin` necessary to run the extension:
- libSimpleRunnerDriver.dylib

## 4. After making SwiftGodotMacro dynamic, redundant dependency
Driver's package:
```
.target(name: "SimpleRunnerDriver",
    dependencies: [
        "SwiftGodot"
        .product(name: "SwiftGodotMacros", package: "SwiftGodot"),
    ],
```
Output of `swift build`:
- libSimpleRunnerDriver.dylib, ~100Kb (SimpleRunnerDriver)
- libSwiftGodot.dylib, ~70 Mb (SwiftGodot)
- libSwiftGodotMacros.dylib, ~70 Mb (SwiftGodotMacros+SwiftGodot)

Contents of `/bin` necessary to run the extension:
- libSimpleRunnerDriver.dylib
- libSwiftGodotMacros.dylib

## 5. After making SwiftGodotMacro dynamic, correct dependency
Driver's package:
```
.target(name: "SimpleRunnerDriver",
    dependencies: [
        .product(name: "SwiftGodotMacros", package: "SwiftGodot"),
    ],
```
Output of `swift build`:
- libSimpleRunnerDriver.dylib, ~100Kb (SimpleRunnerDriver)
- libSwiftGodotMacros.dylib, ~70 Mb (SwiftGodotMacros+SwiftGodot)

Contents of `/bin` necessary to run the extension:
- libSimpleRunnerDriver.dylib
- libSwiftGodotMacros.dylib

**Comment by alicerunsonfedora** [comment]
`SwiftGodotMacros` shouldn't be a dynamic library, and it shouldn't be necessary to copy that over to your project, either. Macros are compiler plugins that ask for expansions in source, and I think having the dynamic target is messing with this a little. I suspect that the work trying to have a single import statement, `import SwiftGodot` might be interfering with the system.

**Comment by tishin** [comment]
Macro implementations (`SwiftGodotMacroLibrary`) aren't necessary, macro declaractions (`SwiftGodotMacros`) are. That's where external part of `#externalMacro` comes into play. To separate macro implementation code and heavy dependencies like `swift-syntax` from being included into the end product.

But you have to include `SwiftGodotMacros` one way or another. In case of static linking, `SwiftGodotMacros` gets embedded into `libSimpleRunnerDriver.dylib`. In case of dynamic linking, `SwiftGodotMacros` is a separate dylib.

**Comment by PadraigK** [comment]
It looks like this is resolved and can be closed cc: @migueldeicaza

**Comment by migueldeicaza** [comment]
@PadraigK thanks, good catch
