### ISSUE TITLE
error: 'shared' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by kropfgames** [migueldeicaza/SwiftGodot#149]
Can you upload a completed version of the tutorial project? I am following the first tutorial. When I build SimpleRunnerDriver with **swift build**, I get the following:

/Users/alex/Desktop/SimpleRunnerDriver/Sources/SimpleRunnerDriver/PlayerController.swift:25:19: error: 'shared' is inaccessible due to 'internal' protection level

When I run the Xcode project, I get the following error:

Swift package target 'SwiftGodot' is linked as a static library by 'SimpleRunnerDriverTests' and 'SwiftGodot', but cannot be built dynamically because there is a package product with the same name.

The PlayerController file has issues:
<img width="887" alt="Screenshot 2023-10-02 at 2 52 14 PM" src="https://github.com/migueldeicaza/SwiftGodot/assets/52729602/cb9f53ff-b551-49b1-bbac-116d24add1c9">

**Comment by PadraigK** [comment]
Ah, `shared` was removed and all of the methods / properties were made static, so you should be able to do e.g. `Input.getActionStrength(action: "move_left")` instead.

**Comment by PadraigK** [comment]
It looks like the issue with `shared` remaining in the tutorial was fixed in: https://github.com/migueldeicaza/SwiftGodot/pull/143

Can you try again with a more recent version?

**Comment by migueldeicaza** [comment]
I believe this is handled
