### ISSUE TITLE
Error: Attempt to register extension class using non-existing parent class 'NSObject'

### ISSUE THREAD

**Issue by lupuchard** [migueldeicaza/SwiftGodot#151]
I'm doing the "Your First Extension" tutorial and trying to adapt it to Linux. When Godot tries to load the extension it gives this error:
```
SWIFT: extension_initialize
PlayerController
NSObject
ERROR: Attempt to register an extension class 'PlayerController' using non-existing parent class 'NSObject'
```

But my PlayerController is inheriting from CharacterBody2D as the tutorial has it:
```
import Foundation
import SwiftGodot
import SwiftGodotMacros

@Godot
class PlayerController: CharacterBody2D {
    var acceleration: Float = 100
    var friction: Double = 100
    ...
```

The only changes I made were for the platform in SimpleRunnerDriver.gdextension and omitting "platforms: [.macOS(.v13)]" in Package.swift.

**Comment by tishin** [comment]
There's an issue with superclass reflection in `SwiftGodot`. I made a simplified example of the current implementation:

```
class Wrapped {}
class Parent: Wrapped {}
class Child: Parent {}

func getSuper<T: Wrapped>(of type: T.Type) -> String? {
    return getSuperType(type: type as AnyObject)
}

func getSuperType (type: AnyObject) -> String? {
    guard let t = Mirror (reflecting: type).superclassMirror?.subjectType else {
        return nil
    }
    return String (describing: t)
}
```

And tested it with
```
XCTAssertEqual(getSuper(of: Child.self), "Module.Parent")
XCTAssertEqual(getSuper(of: Parent.self), "Module.Wrapped")
```
The test passes on macOS, but fails on both Windows and Linux (both classes get `NSObject` as their superclass). I suppose casting generic types to AnyObject on macOS involves some ObjC interop, which can't be done on other platforms.

**Comment by migueldeicaza** [comment]
This is very odd, I do not have any references to NSObject in mycodebase, I wonder what could possibly be it.

**Comment by migueldeicaza** [comment]
@tishin Thank you for tracking this down!

Would you mind trying this version here?   I guess I ran into this issue in the previous incarnation of Swift Godot and had shared this answer:

https://stackoverflow.com/a/66354091/16929

**Comment by migueldeicaza** [comment]
This should be fixed with the PR above

**Comment by tishin** [comment]
Yes, using `Swift._getSuperclass` seems to fix the type registration issue.

But now I'm concerned about this other cast:
https://github.com/migueldeicaza/SwiftGodot/blob/4e8492c4d7466280175ad527ce286ca17d48aed3/Sources/SwiftGodot/Core/Wrapped.swift#L170
Shouldn't it also be broken on other platforms? Or this one is fine since it doesn't involve parent reflection?
