### ISSUE TITLE
Feature: `@SceneTree` macro should infer path when not provided.

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#153]
I type this out a lot: `@SceneTree(path: "CollisionShape2D") var collisionShape: CollisionShape2D!`

Since the name of the thing I'm referencing is identical to its type name, it would be nice to have the option to omit the `path` and abbreviate this to: `@SceneTree var collisionShape: CollisionShape2D!`

**Comment by migueldeicaza** [comment]
This is a bit of duplicate code, I am not exactly happy about having two ways of doing this.

There is already a @BindNode property wrapper (instead of Macro) that should achieve the same binding, and relies on the property name matching the scene node name.

I would love to get there.
