### ISSUE TITLE
Improve Swift PM versioning 

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#167]
It would be useful to be able to pin a SwiftGodot dependency to a specific release using Swift PM as follows:

```
.package(
    url: "https://github.com/migueldeicaza/SwiftGodotKit", from: "0.21.0"
)
```

This requires that there be [a tag named](https://developer.apple.com/documentation/xcode/publishing-a-swift-package-with-xcode#Tag-your-latest-commit) `0.21.0` in the repo, and currently our version numbers are `v0.21`.

**Comment by migueldeicaza** [comment]
Oh, good call.   I will adjust my scripts.

**Comment by migueldeicaza** [comment]
Pushed a 0.21.0 tag out

**Comment by PadraigK** [comment]
Thanks!
