### ISSUE TITLE
@Godot macro and inheritance 

### ISSUE THREAD

**Issue by Matt-Is-Confused** [migueldeicaza/SwiftGodot#168]
I attempted to create a base node that I could extend in inheriting nodes
``` Swift
@Godot
class Weapon: Node3D {}

@Godot
class UtilityWeapon: Weapon {}
```
This produces the following error
```
UtilityWeapon.swift:4:1: note: in expansion of macro 'Godot' here
class UtilityWeapon: Weapon {}
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/folders/9r/m4y_6wnd0dl9s__40w5yv5n80000gn/T/swift-generated-sources/@__swiftmacro_2XI6Weapon5GodotfMm_.swift:10:12: note: attempt to override property here
static var _initClass: Void = {
```

Removing the macro from the base class does allow it to compile. I am also able to create the nodes in the editor. I am unsure of what functionality is lost by not manually implementing the init code for the base class. Since I don't plan to spawn and use the base class this probably(?) wont be a problem.

**Comment by migueldeicaza** [comment]
Great scenario.  Let me think about how I want to solve this.

**Comment by Matt-Is-Confused** [comment]
A question I just thought of. Does an inheriting class need to re-announce callables and signals from it's baseclass?

**Comment by migueldeicaza** [comment]
It should, yes.

**Comment by PadraigK** [comment]
I was thinking about this — what if the `GodotObject` gains a requirement for a static `initClass` block with a default empty implementation. Then the `init` would be code-genned to always call `let _ = Self.initClass()`

The `@Godot` macro would then just create an `initClass` implementation and never generate initializers. Then it wouldn't be stepping on the subclasses own usage of initializers.

**Comment by migueldeicaza** [comment]
Oh, I like this plan.

**Comment by EstevanBR** [comment]
Just ran into this :)

**Comment by migueldeicaza** [comment]
Kudos to @PadraigK for submitting the fix.
