### ISSUE TITLE
Add @discardableResult to more functions

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#169]
We've discussed this a little on Slack, but I wanted to start an issue for it here so I can start noting some functions that would benefit from it. 

Since this API is essentially designed around with GDScript where everything is silently ignorable, I would argue that we were in a better place from a Swift ergonomics point of view when we were over-applying `@discardableResult`.

Anyway today I hit:
`CharacterBody2D.moveAndSlide()` — returns a bool (true is there was a collision) but I don't care about the result value. Its not even an error in this case, so there's not really much benefit to forcing me to acknowledge and handle the result.

**Comment by migueldeicaza** [comment]
I think this matches the principle that has been discussed on various forums.  Happy to do those adjustments.

I am not sure that we need an issue open, happy to take pull requests or just have those requests on the forum.

**Comment by PadraigK** [comment]
Alright, sounds good. Just to clarify the plan, is the idea that we'll have a list of methods that we add `@disardableResult` to?

**Comment by migueldeicaza** [comment]
Yes, these are so easy to add, I don't think we need an issue for all of them, we can just have one per request.

The principle is: if the return value is not something that must be acted upon, but it is merely a nice-to-have, then it can be made discardable
