### ISSUE TITLE
Can't access certain methods on the ProjectSettings singleton

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#171]
I need to call `getPropertyList()` on the ProjectSettings singleton, but the `shared` singleton var is not marked `public` so I can't reach it in my code. 

I suspect the reason that the `getPropertyList()` method is not being generated as a static function is because it is provided by a superclass of `ProjectSettings` rather than `ProjectSettings` itself.

**Comment by migueldeicaza** [comment]
Mhm, this is an interesting puzzle.

I am afraid that I need to expose shared, and makes me wonder if we should expose the instance methods as well, just to be safe.
