### ISSUE TITLE
`Vector2i` operators return `Vector2`

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#172]
I expect the return type here to be `Vector2i` but maybe I'm missing some nuance.

`public static func * (lhs: Vector2i, rhs: Double) -> Vector2`

**Comment by Matt-Is-Confused** [comment]
I am not sure if that operation is meant to implicitly cast but generally using a double on an int results in an error `error: binary operator '*' cannot be applied to operands of type 'Int' and 'Double'`.
In languages that do implicitly cast for operators I think the norm is to cast to Double to retain the precision of the double

In this case you might have to cast the double into an Int first

**Comment by PadraigK** [comment]
Hmm.. yeah looking over the rest of the generated code in this class and some of them return Vector2i and some don't. I think you're right and this is intentional. Thanks!
