### ISSUE TITLE
`Rect2i.end` always returns an empty rect, works in GDScript

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#173]
```
# GDScript
var rect = Rect2i(0, 0, 100, 100)
print(rect.end) 
# → (100, 100)
```

```
// Swift
let rect = Rect2i(x: 0, y: 0, width: 100, height: 100)
GD.print(rect.end)
// → Vector2i(x: 0, y: 0)
```

**Comment by PadraigK** [comment]
workaround: 

```
extension Rect2i {
    var end: Vector2i {
        .init(
            x: position.x + size.x,
            y: position.y + size.y
        )
    }
}
```

(I'm not sure why the compiler doesn't complain about me shadowing `end` without an override keyword 🤔)

**Comment by tishin** [comment]
The core problem seems to be that Generator assumes `Rect2i` to have `end` as a stored property based on the `builtin_classes` in `extension_api.json`:
```
"name": "Rect2i",
"is_keyed": false,
"members": [
	{
		"name": "position",
		"type": "Vector2i"
	},
	{
		"name": "size",
		"type": "Vector2i"
	},
	{
		"name": "end",
		"type": "Vector2i"
	}
],
```
But in the `builtin_class_member_offsets` it only has the first two members:
```
"name": "Rect2i",
"members": [
	{
		"member": "position",
		"offset": 0,
		"meta": "Vector2i"
	},
	{
		"member": "size",
		"offset": 8,
		"meta": "Vector2i"
	}
]
```
which is closer to the C implementation, since there's just getter and setter for `end`:
```
_FORCE_INLINE_ void set_end(const Vector2i &p_end) {
	size = p_end - position;
}

_FORCE_INLINE_ Vector2i get_end() const {
	return position + size;
}
```
So the fix would be to take into account only members listed in `builtin_class_member_offsets` to make sure stored properties on Swift side match the C memory layout (There're probably some other issues caused by extra properties not expected by Godot). Not sure what to do with `end` though. I don't see any way to generate the implementation based on `extension_api.json`, so probably we have to implement it manually on non-generated side.

**Comment by PadraigK** [comment]
> So the fix would be to take into account only members listed in builtin_class_member_offsets to make sure stored properties on Swift side match the C memory layout (There're probably some other issues caused by extra properties not expected by Godot). 

👍  As a first step, this would be an improvement because the property would be missing rather than silently broken.

>  Not sure what to do with end though. I don't see any way to generate the implementation based on extension_api.json, so probably we have to implement it manually on non-generated side.

I don't have much experience calling C from Swift, so maybe this isn't possible but: In these cases, where there's no entry in `builtin_class_member_offsets`, could we assume that they're going to have getter/setters and generate a set of swift getters and setters that forward to the C implementation?

**Comment by PadraigK** [comment]
Also thanks for investigating and explaining! 🥇

**Comment by tishin** [comment]
> I don't have much experience calling C from Swift, so maybe this isn't possible but: In these cases, where there's no entry in `builtin_class_member_offsets`, could we assume that they're going to have getter/setters and generate a set of swift getters and setters that forward to the C implementation?

The problem is: those setters and getters are not described in `extension_api.json`. For reference types properties with setters and getters are described in the following manner:
```
"properties": [
	{
		"type": "Rect2i",
		"name": "region",
		"setter": "set_region",
		"getter": "get_region"
	},
```
And there's no such description for `end`.

**Comment by PadraigK** [comment]
Should we file an issue upstream so that the setter/getter can be added to `extension_api.json` ?

**Comment by migueldeicaza** [comment]
We could request the features, it won't hurt, but we can also add extensions that make sense for us to have in our codebase.

In addition to the above, I want to also have pure Swift-implementations of certain methods, to avoid the round trip to C++ via the glue layer.   In particular for things in Vector*/Rect* methods.   If we are missing things, is mostly a function of time, and not a matter of principle :-)

**Comment by tishin** [comment]
By the way, @migueldeicaza is there any sort of documentation on how to interpret `extension_api.json`? I'd love to read that to make sure we even understand what we're doing before jumping to any conclusions that something is missing.

**Comment by PadraigK** [comment]
> We could request the features, it won't hurt, but we can also add extensions that make sense for us to have in our codebase.

I'm in favour of our own extensions, I am also worried that there are other examples like `end` that might be missing; It'd be good to know that the json file was complete as a base layer, even if we choose to add nicer API on top later.
