### ISSUE TITLE
Can't reference SwiftGodot using `.package(url: … from: 0.21.0` 

### ISSUE THREAD

**Issue by PadraigK** [migueldeicaza/SwiftGodot#175]
If I add SwiftGodot as a dependency pointing to `branch: "main"` everything works, but if I use the `.package(url: "https://github.com/migueldeicaza/SwiftGodot", from: "0.21.0")` syntax, then `swift package update` fails with:

```
> error: the target 'SwiftGodot' in product 'SwiftGodot' contains unsafe build flags
```

I reviewed the commits between the `0.21.0` tag and `main` and they do not change anything in the Package file. I looked into it and it turns out that [Swift PM handles these two differently](https://forums.swift.org/t/question-about-contains-unsafe-build-flags-in-spm/47677).

This means that we will either need to get rid of the unsafe flags in the Swift Godot package, or we will not be able to use release tags.

--- 

The unsafe flags, for reference:
```
.unsafeFlags([
    "-Xlinker", "-undefined",
    "-Xlinker", "dynamic_lookup",
])
```

**Comment by alicerunsonfedora** [comment]
I've been running into this as well, and I believe I documented it in an earlier issue (#52, I think?). A workaround I've been using is referencing the commit hash of the tag in question, rather than the tag itself

**Comment by PadraigK** [comment]
Right, that works, but we ideally ought to have standard release conventions, so I think it's important to figure this out.

**Comment by migueldeicaza** [comment]
This is tentatively working now with the suggested approach
