### ISSUE TITLE
Issue with docs on exporting nodes and resources 

### ISSUE THREAD

**Issue by KPidS** [migueldeicaza/SwiftGodot#191]
This was copied from C# docs and wasn't changed, literally C# code, I was super confused by this: https://github.com/migueldeicaza/SwiftGodot/blob/main/Sources/SwiftGodot/SwiftGodot.docc/Exports.md#nodes

This doesn't work: 

```swift
@Export
public var resource: Resource { get { } set { } }

@Export
public var node: Node { get { } set { } }
```

```
error: missing return in getter expected to return 'Resource'
        get {}
             ^
error: missing return in getter expected to return 'Node'
        get {}
             ^
```

**Comment by migueldeicaza** [comment]
These were intended to be examples of what the declaration would look like.

I'll add some '...' in there.
