### ISSUE TITLE
Support Hot Reloading

### ISSUE THREAD

**Issue by Matt-Is-Confused** [migueldeicaza/SwiftGodot#192]
The upcoming Godot 4.2 release will include support for live reloading GDExtensions.
The Godot PR that implemented this is here https://github.com/godotengine/godot/pull/80284
The Godot-cpp implementation can be found here https://github.com/godotengine/godot-cpp/pull/1200

**Comment by PadraigK** [comment]
In case it helps provide context to anyone:

My experience _today_ (before 4.2) is that it hot reloads everything when I copy in my dylib. The only exception is when I add a new type to the `#initSwiftExtension` — in that case I need to tell the editor to reload the project manually. I hope the new Godot changes give us that last piece, it would be nice to never need to reload.

**Comment by migueldeicaza** [comment]
This patch contains:

(a) Upgrade to the 4.2 API
(b) Unrelated: locking for internal table access
(c) Hot-reload support.

https://gist.github.com/migueldeicaza/1884e40a485ade88eff8b4a4c762e0d9

**Comment by migueldeicaza** [comment]
Splitting the (b) part

**Comment by migueldeicaza** [comment]
Ok, hot reload is implemented on main, but I have not tested it, would love if someone could take it for a spin.
