### ISSUE TITLE
Unable to export for iOS using prebuilt XCFramework

### ISSUE THREAD

**Issue by alicerunsonfedora** [migueldeicaza/SwiftGodot#193]
There appears to be an issue with exporting a project for iOS using the prebuilt xcframework, with code-signing causing a build failure:

```
CodeSign /Users/marquis/Library/Developer/Xcode/DerivedData/Indexing_Your_Heart-bttmidcbbduwbhgfyqkzsweyugbc/Build/Products/Debug-iphoneos/Indexing\ Your\ Heart.app/Frameworks/SwiftGodotCore.framework/Versions/A (in target 'Indexing Your Heart' from project 'Indexing Your Heart')
    cd /Users/marquis/Developer/IndexingYourHeart/.dist
    
    Signing Identity:     "Apple Development: Marquis Kurt (XXXXXXXXXX)"
    Provisioning Profile: "iOS Team Provisioning Profile: art.indexingyourhe.game"
                          (XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)
    
    /usr/bin/codesign --force --sign XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --timestamp\=none --preserve-metadata\=identifier,entitlements,flags --generate-entitlement-der /Users/marquis/Library/Developer/Xcode/DerivedData/Indexing_Your_Heart-bttmidcbbduwbhgfyqkzsweyugbc/Build/Products/Debug-iphoneos/Indexing\ Your\ Heart.app/Frameworks/SwiftGodotCore.framework/Versions/A

/Users/marquis/Library/Developer/Xcode/DerivedData/Indexing_Your_Heart-bttmidcbbduwbhgfyqkzsweyugbc/Build/Products/Debug-iphoneos/Indexing Your Heart.app/Frameworks/SwiftGodotCore.framework/Versions/A: bundle format unrecognized, invalid, or unsuitable
Command CodeSign failed with a nonzero exit code

Command CodeSign failed with a nonzero exit code
```

![image](https://github.com/migueldeicaza/SwiftGodot/assets/13445064/1efb6527-1006-4aad-8470-7100e5845683)

It seems as if the framework generation for iOS might be missing information, or it is malformed.

| What Godot exported | What appears in xcframework |
| --- | --- |
| ![image (1)](https://github.com/migueldeicaza/SwiftGodot/assets/13445064/5e9ec155-d944-4d06-9dbe-07da7b401639) | ![image (2)](https://github.com/migueldeicaza/SwiftGodot/assets/13445064/ac976b5d-0a47-40e1-b719-0c9ab8605af7) |

If I were to change the framework's setting to "Embed without Signing" (or match the structure as described in Apple's documentation), it will build and attempt to install, but then I get greeted with an error about a certificate, which never appears in Settings > General > VPN & Device Management, as the error suggests.

![image (3)](https://github.com/migueldeicaza/SwiftGodot/assets/13445064/df81f1e4-f37f-47f1-9f33-ca858b685d16)

However, if I were to change the framework such that it matches my other ones (just an Info.plist and an executable), which are getting signed, it will build and launch, but crash immediately:

```
dyld[5689]: Library not loaded: @rpath/SwiftGodot_6FA7224D83C68214_PackageProduct.framework/SwiftGodot_6FA7224D83C68214_PackageProduct
  Referenced from: <146AF390-5FA6-3164-BCA7-6BABFF08F18C> /private/var/containers/Bundle/Application/73DEB564-273A-41DC-93EB-1032E5F69D27/Indexing Your Heart.app/Frameworks/Demoscene.framework/Demoscene
  Reason: tried: '/private/var/containers/Bundle/Application/73DEB564-273A-41DC-93EB-1032E5F69D27/Indexing Your Heart.app/Frameworks/SwiftGodot_6FA7224D83C68214_PackageProduct.framework/SwiftGodot_6FA7224D83C68214_PackageProduct' (no such file), '/private/var/containers/Bundle/Application/73DEB564-273A-41DC-93EB-1032E5F69D27/Indexing Your Heart.app/Frameworks/SwiftGodot_6FA7224D83C68214_PackageProduct.framework/SwiftGodot_6FA7224D83C68214_PackageProduct' (no such file)Library not loaded: @rpath/SwiftGodot_6FA7224D83C68214_PackageProduct.framework/SwiftGodot_6FA7224D83C68214_PackageProduct
  Referenced from: <E747C944-DE5A-3125-9628-A1F160723195> /private/var/containers/Bundle/Application/73DEB564-273A-41DC-93EB-1032E5F69D27/Indexing Your Heart.app/Frameworks/Rollinsport.framework/Rollinsport
  Reason: tried: '/private/var/containers/Bundle/Application/73DEB564-273A-41DC-93EB-1032E5F69D27/Indexing Your Heart.app/Frameworks/SwiftGodot_6FA7224D83C68214_PackageProduct.framework/SwiftGodot_6FA7224D83C68214_PackageProduct' (no such file), '/private/var/containers/Bundle/Application/73DEB564-273A-41DC-93EB-1032E5F69D27/Indexing Your Heart.app/Frameworks/SwiftGodot_6FA7224D83C68214_PackageProduct.framework/SwiftGodot_6FA7224D83C68214_PackageProduct' (no such file)
```

<img width="1069" alt="image" src="https://github.com/migueldeicaza/SwiftGodot/assets/13445064/12d27d85-907c-46c2-a6b6-3878da0542fc">

Steps to reproduce:

- Create a project that uses the prebuilt SwiftGodot.xcframework (or [SwiftGodotCore.xcframework, in my case](https://gitlab.com/indexing-your-heart/engine/SwiftGodotCore/-/releases/1.0.0-alpha22-hotfix1/downloads/SwiftGodotCore.xcframework.zip)).
- Use xcodebuild to create frameworks for iOS and copy them into a Godot project.
- Create an export template for iOS and export it.
- Try to open the created Xcode project and run it (either for simulator or a real device).

Easier steps, for those with Apple Silicon Macs:
- Clone https://gitlab.com/indexing-your-heart/game with `git clone --recursive`.
- Follow the build instructions to build the extensions.
- Create an export template for iOS and export the project.
- Open the created Xcode project for iOS and attempt to run it for a real device.

**Comment by migueldeicaza** [comment]
That seems to be an issue with your custom build of the framework, because this is what is currently posted on GitHub:

<img width="1090" alt="image" src="https://github.com/migueldeicaza/SwiftGodot/assets/36863/dabad0f4-ebc2-45b5-84d8-41a1c3fdaca9">

**Comment by alicerunsonfedora** [comment]
After some investigation, it does appear there were some other shenanigans on my end:

- First, I needed to reformat the iOS framework to match what Xcode expects (I added this to the end of `make-swiftgodot-framework`):
```bash
# Reformat iOS framework
echo "[Step] Reformatting iOS framework for code signing."

cp $fd/Modules/module.modulemap $ifd/Versions/Current/Modules/module.modulemap
cp $fd/Headers/$framework-Swift.h $ifd/Versions/Current/Headers/$framework-Swift.h
cp $fd/Headers/$framework.h $ifd/Versions/Current/Headers/$framework.h

cwd=`pwd`
cd $ifd
rm -f Headers Modules
mv Versions/Current Versions/A
cp Info.plist Versions/A/
rm -rf Versions/Current
mv $framework Versions/A
ln -sf Versions/A Versions/Current
ln -sf Versions/A/$framework $framework
ln -sf Versions/A/Headers Headers
ln -sf Versions/A/Modules Modules
cd $cwd
```

- Next, there were _additional_ libraries missing on my end because of the way my project is structured. Notably, the logger and SwiftGodot "meta" package of mine were missing, hence not able to load. Adding these into the exported Xcode project works as expected (minus a crash I'm facing due to bootstrapping a logger one too many times).
