### ISSUE TITLE
Debug speed of Swift 100x slower than Release

### ISSUE THREAD

**Issue by alecazam** [migueldeicaza/SwiftGodot#220]
Just watched your talk from GodotCon 23, and really enjoyed it.  I went down the Swift path with a small renderer, and I've written many.  And was not impressed by the debug speed of Swift.   It was 100x slower than Release, and most devs like to work in a debug build.  So I'm unsure of moving Godot as this large C++ engine over to Swift.   Maybe the renderer stays C++ and fast, and just the UI Editor/Gui moves.   Just curious about your thoughts about this.

**Comment by Matt-Is-Confused** [comment]
If you are willing to trade build time for speed, `swift build` can be passed `-Xswiftc -O` and/or `-whole-module-optimization`

**Comment by migueldeicaza** [comment]
The proposal from my talk was to merely move the Editor, not the engine.

The reason is that it would be easier to do that for the editor, as it is only effectively used in a handful of platforms, vs the engine that has deeper impacts.

**Comment by alecazam** [comment]
Still feels like a workaround to a major problem in Swift.   So I think this should be presented to game devs before pushing them to Swift.
