### ISSUE TITLE
Auto Register custom Nodes

### ISSUE THREAD

**Issue by Ansraer** [migueldeicaza/SwiftGodot#229]
We talked about this for a bit after your talk at GodotCon23, but didn't have time to go too far into it.

Basically, what I am proposing is that we use code generation to automatically register every class that has the ´@Godot´ and inherits (directly or indirectly) from ´Node´. By doing this we would remove the burden of having to register everything manually from the user, something I personally have forgotten to do more often than I would care to admit.

**Comment by migueldeicaza** [comment]
I think I could auto-register on first use, in the constructor, but I am not sure how to do this without first creating a class.

I will close, as there is an existing issue here: https://github.com/migueldeicaza/SwiftGodot/issues/40
