### ISSUE TITLE
When using @Godot macro, should check to see if required init() methods are there, and skip generating

### ISSUE THREAD

**Issue by pcbeard** [migueldeicaza/SwiftGodot#250]
I'd like to be able to use the @Godot macro, but optionally provide a parameterless init() method. The @Godot macro should check to see if the init() is already there, and skip generating it if so.

**Comment by PadraigK** [comment]
I think this can be closed, as @Godot no longer generates inits at all: https://github.com/migueldeicaza/SwiftGodot/pull/234

**Comment by migueldeicaza** [comment]
Thank you @PadraigK closing this issue.
