### ISSUE TITLE
Warnings in @Export macro for custom types

### ISSUE THREAD

**Issue by adamjcampbell** [migueldeicaza/SwiftGodot#252]
## Reproduction 1

Create a custom resource class
```swift
@Godot
final class MyData: Resource {}
```

Export this custom class on another Godot type:
```swift
@Godot
final class MyClass: Node {

    @Export var data: MyData = .init()

}
```

This will produce the following warnings:
```swift
Conditional cast from 'MyData' to 'RefCounted' always succeeds
Conditional cast from 'MyData' to 'RefCounted' always succeeds
Result of call to 'reference()' is unused
Result of call to 'unreference()' is unused
```

## Example 1

<img width="1512" alt="Screenshot 2023-11-25 at 9 59 37 am" src="https://github.com/migueldeicaza/SwiftGodot/assets/5327203/bace426c-cae0-47c5-9e80-24f99d4b5113">

## Reproduction 2

Export a non RefCounted Godot type:
```swift
@Godot
final class MyClass: Node {

    @Export var node: Node2D = .init()

}
```

This will produce the following warnings:
```swift
Cast from 'Node2D' to unrelated type 'RefCounted' always fails
Cast from 'Node2D' to unrelated type 'RefCounted' always fails
Result of call to 'reference()' is unused
Result of call to 'unreference()' is unused
```

## Example 2

![Screenshot 2023-11-26 at 4 40 47 pm](https://github.com/migueldeicaza/SwiftGodot/assets/5327203/6e433425-b346-4c12-bf29-5b06f2a205fd)

## Proposed solution

Update the macro to generate something akin to:

```swift
    func _mproxy_set_example(args: [Variant]) -> Variant? {
        let oldRef = (example as Any) as? RefCounted

        if let res: Node2D = args[0].asObject() {
            _ = ((res as Any) as? RefCounted)?.reference()
            example = res
        }

        _ = oldRef?.unreference()

        return nil
    }
```

- Explicitly casting to `Any` removes any warnings associated with conditional casting
- Uses `_ = ` to silence the result unused warnings

### Open questions

- The generated function here always returns nil, should this be updated to a `Void` function?
- Could we add `@discardableResult` to the generated `reference` and `unreference` functions as an alternative?

**Comment by EstevanBR** [comment]
I tend to favor `@discardableResult` over `_ = `

**Comment by adamjcampbell** [comment]
I agree if we can generate the required functions with `@discardableResult` easy enough then we should prefer it

Also I'll note that I don't love casting to `Any` but I'm not sure there's a great way around it. We can't really detect what types conform to `RefCounted` in the context of a macro. Unless we want to use a parameter perhaps

**Comment by migueldeicaza** [comment]
The cast to Any and then to probe incurs in an additional 28 instructions on ARM, six of those are new branch/calls, and one call to _swift_dynamicCast which is an expensive function to invoke.

So I would not likely change the code to use the Any.   What we could try is to instead drop the 'as?' cast, which should always be ok, and only live with uglier errors for the case when it does not pan out.

**Comment by migueldeicaza** [comment]
I made the returns discardable for reference/unreference.

**Comment by migueldeicaza** [comment]
Idea: we could add methods to the base class 'asRefcounted' and 'asObject' that perform these operations to silence the compiler.

Another option is to load the entire hierarchy of RefCounted objects into the macro processor to determine which path to generate, but that would only help for built-in types.   User-defined types would still produce the warning.

**Comment by migueldeicaza** [comment]
I asked on the Slack for Swift Open Source, and using the following function as a local function keeps the code size identical, but eliminates the warning:

```
func dynamicCast<T, U>(_ value: T, as type: U.Type) -> U? { value as? U }
```

This could be used for the "foo as? Ref

**Comment by migueldeicaza** [comment]
This should be fixed

**Comment by adamjcampbell** [comment]
@migueldeicaza just catching up on this, awesome work
> The cast to Any and then to probe incurs in an additional 28 instructions on ARM, six of those are new branch/calls, and one call to _swift_dynamicCast which is an expensive function to invoke.

What's your usually workflow to track instruction count?
