### ISSUE TITLE
Exported Arrays do not render properly, and sometimes print garbage to the editor.

### ISSUE THREAD

**Issue by EstevanBR** [migueldeicaza/SwiftGodot#277]
Repro:

With this class
```swift
@Godot
class Inventory: Node {
    @Export var guns: Int = 9
    @Export var weight: Float = 22.0
    @Export var connections: VariantCollection<String> = ["Module 1 -> Module 2", "Module 3 -> Module 7"]
    @Export var checkIns: ObjectCollection<Node3D> = [.init()]
    @Export var address: String = "1234 Fake St"
    @Export var daysOfOperation: VariantCollection<String> = ["Mon", "Tue", "Weds", "Thurs"]
    @Export var hours: VariantCollection<String> = ["9am-5pm", "9am-5pm", "9am-5pm", "9am-5pm"]
    @Export var insuranceProvidersAccepted: ObjectCollection<Control> = [.init(), .init()]
}
```

Try and expand the various exported collections in the editor.

- exported String collections show empty strings
- exported Object collections also seem to show empty

(ignore the export categories, that was part of another issue I'm working on)
<img width="498" alt="image" src="https://github.com/migueldeicaza/SwiftGodot/assets/5488655/fe123b87-9014-47c9-96f6-d24bc812384c">

<img width="788" alt="image" src="https://github.com/migueldeicaza/SwiftGodot/assets/5488655/f42a9fd4-9b35-4b12-8aa1-43ea99c53f98">

**Comment by EstevanBR** [comment]
I'm quite sure that 2464c92ce8b83078c8fb7585e44f8e0d77cc1282 resolves hit

**Comment by migueldeicaza** [comment]
Wooohooo!
