### ISSUE TITLE
GDExtension

### ISSUE THREAD

**Issue by ShalokShalom** [migueldeicaza/SwiftGodot#285]
Which API does this project using?

I do care for a list of projects, that provide language support to Godot.
It is one of our goals, to include the information about the used API.

https://github.com/Vivraan/godot-lang-support

**Comment by migueldeicaza** [comment]
main tracks Godot 4.2, and the 4.1 branch contains support for 4.1.

Support for 4.0 was not tagged, but someone can dig it up if they need to :-)
