### ISSUE TITLE
BindNode crash issue

### ISSUE THREAD

**Issue by Kyle-Ye** [migueldeicaza/SwiftGodot#289]
For `@BindNode var pivot: Node3D`, the name we'll get in the implementation of `BindNode` is `_privot` via `storageKeyPath.debugDescription`. This is not expected and will cause a crash.
 
Two workarounds IMO:
- Rename the node in Godot Editor from "privot" to "_privot"
- Use `getNode` directly
```swift
let nodePath = NodePath(from: "pivot")
let privot = getNode(path: nodePath) as! Node3D
```

**Comment by migueldeicaza** [comment]
Is there a typo here in `pivot` vs `privot`?

Or is the issue here that the actual name being used by the implementation is the `_pivot`?

If this is the later, I wonder if something changed, can you check what `wrappedKeyPath` is?

**Comment by Kyle-Ye** [comment]
> Is there a typo here in `pivot` vs `privot`?
> 
> Or is the issue here that the actual name being used by the implementation is the `_pivot`?
> 
> If this is the later, I wonder if something changed, can you check what `wrappedKeyPath` is?

Yes, it is a typo.

The `wrappedKeyPath` is the correct value without underscore. See #290 's screenshot.
