### ISSUE TITLE
[help] Tutorial project in Xcode stuck in "Indexing | processing files"

### ISSUE THREAD

**Issue by E-ricus** [migueldeicaza/SwiftGodot#307]
Thanks for this project! This was exactly what I needed to get introduced to swift, the tutorial docs are really great and easy to follow, but I gotta say the Xcode experience has not been great, I'm curious if anyone has experienced something similar.

As I mentioned, I'm learning Swift while doing a small game with godot, so it is my first time using Xcode, and I'm used to a different developer experience, but I wanted to follow at least the tutorial using the editor to be familiar with the ecosystem.

When writing the extension, I noticed that the auto-completion was not giving me any information about types or the macros I could use from this library, I thought that maybe for Swift was not possible to give info in these, so I continued without it, but when I got to the point of building, I got some errors, due to some typos on my part, so it was not only missing completion but code analysis in general. As I was not used to use this editor, I didn't notice that in the top bar the project status was stuck on `Indexing | processing files` looking for similar issues, apparently it happens when there is something "wrong" with the swift code.

So, I configured the sourcekit lsp in neovim, and there, I got the completion, info on the Godot types and macros, errors report, all fine. I finished the extension, build it without an issue, and got it working in the godot editor, so no problem with the code nor the library. 
Then it has to be xcode I thought, so I created the iOS app and cli projects from Swift's getting started, and both of them work just fine, the indexing finished, and the code analysis works as expected. Also creating a small cli from the terminal adding a dependency, writing it in neovim, building it, and open the project with xcode the indexing finishes and I get all the info.

So I think it is the combination of this dependency used in my xcode editor I've tried reinstalling xcode, cleaning cache, but it always gets stuck there, and I'm not sure where to look now, so any help for someone more experienced with xcode will be appreciated!

My system: 
MacOS Sonoma 14.2
Xcode 15.1
Swift 5.9.2

Thanks!

**Comment by migueldeicaza** [comment]
Code completion usually requires an initial build of SwiftGodot.

So start by creating a very simple program, with no statements in it, just reference the library, and hit "Build".

That will trigger the compilation, and Xcode will ask "Do you want to trust the macros?" and you should agree to that.

Code completion should work after that.

We probably need to update the documentation to reflect this - if it works, let me know, what was missing, so I can change it.

**Comment by E-ricus** [comment]
That did the trick!

Interesting! The build from Xcode differs from the build done by the swfit command, I thought that just by having a successful build the editor would be able to index it with it, and as I'm used to building in the terminal it didn't occurred to me to try building in Xcode, but all worked afterward, thanks for the help!!

I'd say someone with experience with the editor and/or swift will already know the building difference and identify the issue, it might seem redundant for someone to see as one of the steps something like "click build from within Xcode", but for newcomers to the ecosystem might be useful
