### ISSUE TITLE
`@Callable` add support for returning `VariantCollection` and `ObjectCollection`

### ISSUE THREAD

**Issue by EstevanBR** [migueldeicaza/SwiftGodot#310]
If a `VariantCollection<Element>` is a return type, we get an error.
If a `ObjectCollection <Element>` is a return type, we get an error.

Related issues:
- #310
- #313
- #314
- #315

**Comment by EstevanBR** [comment]
Questions:
- for exported properties / variables, we had to use Variant and Object collections, but for a function, are we limited in the same way? or can the function signature return an array type? (regardless we probably still need to handle Variant and Object Collections)
- do we just need to make VariantCollection and ObjectCollection conform to VariantRepresentable so that the existing macro can continue to use `Variant (result)` where result is a VariantCollection or an ObjectCollection

**Comment by migueldeicaza** [comment]
Merged the LR
