### ISSUE TITLE
`@Callable` add support for params of type `VariantCollection<Element>` and `ObjectCollection<Element>`

### ISSUE THREAD

**Issue by EstevanBR** [migueldeicaza/SwiftGodot#313]
If a param in a function marked as `@Callable` contains one of these types, an error will be surfaced.
This may be more related to how generics are handled. As I think makeOrUnwrap might actually be available on these specialized types, but the specialization is not being passed into the expanded macro.

Related issues:
- #310
- #313
- #314
- #315

**Comment by migueldeicaza** [comment]
Closing per PR
