### ISSUE TITLE
`@Callable` add support for Swift Array return types whose Element conforms to `VariantStorable`

### ISSUE THREAD

**Issue by EstevanBR** [migueldeicaza/SwiftGodot#314]
`@Callable` macro currently does not support functions that returns `[Vector3]` or `[Node3D]` for example.
As long as the element is able to be stored or represented as a Variant, we can construct either a GArray or a Variant/ObjectCollection for it in the macro proxy method.

Related issues:
- #310
- #313
- #314
- #315

**Comment by migueldeicaza** [comment]
Closing per PR
