### ISSUE TITLE
Vector2 Crashes When Using Operators

### ISSUE THREAD

**Issue by JustinSharkey** [migueldeicaza/SwiftGodot#32]
Setup: I have been using the SimpleExtension in SwiftGodotKit to create a bundle and then use that in a Godot project.

This issue occurs after running the game from the Godot IDE. 

When doing equals or multiplication operations (I haven't tried others) with a Vector2 crashes the game.

I've attached a 
* screenshot of the code that crashed next to their workarounds
* a screenshot of the crash log
*  a zip with two crashlogs.

<img width="752" alt="Screenshot 2023-04-22 at 5 48 29 PM" src="https://user-images.githubusercontent.com/3056529/233838817-4bae135f-ecb5-4fcf-a9f7-e2f81af7a124.png">
<img width="816" alt="Screenshot 2023-04-22 at 5 52 12 PM" src="https://user-images.githubusercontent.com/3056529/233838815-7770ae96-a399-4c95-90de-9919cf171d9f.png">
[Archive.zip](https://github.com/migueldeicaza/SwiftGodot/files/11303675/Archive.zip)

**Comment by migueldeicaza** [comment]
Thank you for the report.  I am traveling but will be back home in two days and fix it

**Comment by migueldeicaza** [comment]
Thank you for the bug report, it has now been fixed, let me know if I missed anything.

Cheers!
