### ISSUE TITLE
Parameterless methods such as `_ready()` and `_enterTree()` not called.

### ISSUE THREAD

**Issue by JustinSharkey** [migueldeicaza/SwiftGodot#33]
Setup: I have been using the SimpleExtension in SwiftGodotKit to create a bundle and then use that in a Godot project.

When subclassing `Node` and overriding parameterless methods such as `_ready()` or `_enterTree()` they are not called. However, when overriding `_input(event:)` that function is called.

In `ClassGen.L96` ([link](https://github.com/migueldeicaza/SwiftGodot/blob/main/Generator/Generator/ClassGen.swift#L96)) there is `p ("guard let args else { return }")` which stops parameterless functions from continuing.

**Comment by migueldeicaza** [comment]
I think the PR fixes this
