### ISSUE TITLE
Extension subclasses run in editor

### ISSUE THREAD

**Issue by tishin** [migueldeicaza/SwiftGodot#347]
In GDScript scripts don't run in editor by default, there's a special annotation for that: [`@tool`](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html)

That's not the case for GDExtension. I assume, it's by design that bindings have to implement game and editor logic separation.
For example, in Rust bindings subclasses don't run as tools by default, but [can be declared as such](https://godot-rust.github.io/docs/gdext/master/godot/prelude/derive.GodotClass.html#running-code-in-the-editor). 

Currently Swift subclasses run in editor, and the only way I know of to work around that is to use `Engine.isEditorHint()` checks in gameplay code. I think it's counterintuitive, and can lead to a lot of confusion (#77, for example).

**Comment by tishin** [comment]
There's a PR in Godot repo addressing this issue: https://github.com/godotengine/godot/pull/82554

**Comment by EstevanBR** [comment]
I've ran into this too, and it was very confusing. I'd  also like the option have similar `@tool` functionality in SwiftGodot
