### ISSUE TITLE
Unary minus operators aren't being generated

### ISSUE THREAD

**Issue by tishin** [migueldeicaza/SwiftGodot#356]
In GDScript it's possible to use [unary minus](https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3-operator-unminus) operators for negation, e.g. `print(-Vector3(1, 2, 3))` will output `(-1, -2, -3)`.
Currently we skip all unary operators during generation. Not sure if we need "unary plus" or "not" operators though.

**Comment by migueldeicaza** [comment]
It seems like we should omit plus, the negation would be nice, but not as important as the negation one.

that said, I feel that we might want to do manual extensions for those methods anyways.
