### ISSUE TITLE
Example in README needs .tool annotation

### ISSUE THREAD

**Issue by cplr** [migueldeicaza/SwiftGodot#369]
Since the new feature to declare a GDExtension as a "tool" in https://github.com/migueldeicaza/SwiftGodot/pull/351, the spinning cube example on the main README needs this annotation. Otherwise, the cube is not added until you run the scene (in which case you need to add a camera pointed at the new mesh). It is not seen in the editor.

**Comment by migueldeicaza** [comment]
Thank you for spotting this!
