### ISSUE TITLE
PackedByteArray to Data helper function

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftGodot#374]
Currently, I do not expose a "pointer to the array" feature, I could either expose that, or even better, expose a function that returns the Data() for it.

**Comment by tishin** [comment]
@migueldeicaza I believe this was done in https://github.com/migueldeicaza/SwiftGodot/commit/39c67bf8f4f266802010fc2092d513d7918876c4
But maybe it would make more sense to expose a helper function that returns a byte array instead, without introducing `SwiftGodot`'s dependency on `Foundation`?

**Comment by migueldeicaza** [comment]
Yes, let us do that for now

**Comment by migueldeicaza** [comment]
Even better, we could surface a withUnsafeAccess helper method that gives us the pointer and addrsss, so folks can do their own data wrapper easily without copying the daya

**Comment by migueldeicaza** [comment]
Closing, implemented alternative without Foundation dependency.
