### ISSUE TITLE
Food for thought

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftGodot#396]
Should the `GodotError` enumeration adopt the `Error` protocol so that it can be thrown?

**Comment by Matt-Is-Confused** [comment]
Another feature beyond throwing is that Result uses error as well https://developer.apple.com/documentation/swift/result. Result is pretty useful in situations where throwing doesn't conform to the general flow of the program like networking or async/callbacks

**Comment by migueldeicaza** [comment]
Oh, very good point.

**Comment by migueldeicaza** [comment]
Oh, that was already the case, just as an extension.

I cleaned it up a little to make it more obvious, and so I do not trip next time I have this idea.

But I went ahead and added a `debugDescription` to enums as well, as a companion to the OptionSets that already implemented this feature.
