### ISSUE TITLE
Add SwiftGodot documentation tutorial in about section

### ISSUE THREAD

**Issue by jaroshevskii** [migueldeicaza/SwiftGodot#405]
- Add tutorials for SwiftGodot documentation to improve projecе.
- Include a link to the tutorials: [SwiftGodot Tutorials](https://migueldeicaza.github.io/SwiftGodotDocs/tutorials/swiftgodot-tutorials/)

<img width="262" alt="image" src="https://github.com/migueldeicaza/SwiftGodot/assets/72662383/f7ad3ee6-828f-461e-95b8-cce2e500d94f">

**Comment by migueldeicaza** [comment]
How does one do that?

**Comment by jaroshevskii** [comment]
1. Click the customization icon on the project page

<img width="355" alt="image" src="https://github.com/migueldeicaza/SwiftGodot/assets/72662383/9d4f8a6b-092d-4a3a-96f8-7c2752d7440c">

2. In the window that opens, you will be able to specify the link to the web page

<img width="668" alt="image" src="https://github.com/migueldeicaza/SwiftGodot/assets/72662383/2fc896fe-18df-4966-8fbe-086f9f02942b">

**Comment by migueldeicaza** [comment]
Ok, I think I got something in place, is that what you had in mind?

**Comment by jaroshevskii** [comment]
Yep, thanks ☺️
