### ISSUE TITLE
Improve `@Export` to support `Variant` and `GArray` types.

### ISSUE THREAD

**Issue by EstevanBR** [migueldeicaza/SwiftGodot#410]
If you try to `@Export` a `GArray` or a `Variant` you get this error:

### GArray
```swift
if let res: GArray = args [0].asObject () {
```
> `instance method 'asObject' requires that 'GArray' conform to 'GodotObject'`

In this case we'd want `GArray(args[0])`

### Variant
```swift
if let res: Variant = args [0].asObject () {
```
> `instance method 'asObject' requires that 'Variant' conform to 'GodotObject'`

In this case we could just have `if let res = args.first` (IMO we should be using args.first any place we use args[0])

**Comment by migueldeicaza** [comment]
Fascinating, in both cases, those are the incorrect casts.

There is no need of the `asObject` in the `Variant` case, and for the GArray case we need to call `GArray (args[0])` instead.
