### ISSUE TITLE
Unsafe array indexing throughout project

### ISSUE THREAD

**Issue by EstevanBR** [migueldeicaza/SwiftGodot#411]
Feel free to close this issue if it's not valid.

I see things like
```swift
if let res = args[0].asObject() {
```
Which mixes safe code (`if let`) with unsafe array indexing (`args[0]`)

Which would imo be safer as
```swift
if let firstArg = args.first, let res = firstArg.asObject() {
```

**Comment by migueldeicaza** [comment]
Where are you seeing this?

If this is for the generated setter arguments, we have bigger problems if the setter does not get at least one value ;-)

**Comment by migueldeicaza** [comment]
Closing, as it would not improve much per above
