### ISSUE TITLE
Update tags to follow semver `major.minor.patch`,eg `0.40.0` instead of `0.40`

### ISSUE THREAD

**Issue by EstevanBR** [migueldeicaza/SwiftGodot#412]
Currently most tags are `major.minor` format, this PR proposes changing tags to semver conformant tags.

SPM expects packages to follow semantic versioning, as long as the major number is 0, the API can be unstable, but once we hit 1.0.0 I think we'd want to more strictly follow semantic versioning.

Thoughts?

https://semver.org/

**Comment by migueldeicaza** [comment]
I very much agree, I do these by hand, so it is really a matter of remembering :-)

The next one will follow that pattern 0.41.0, 0.42.0 and so on.
