### ISSUE TITLE
Can i use this libirary to embed Godot game to my existing native mobile application or react native ,flutter?

### ISSUE THREAD

**Issue by ducpt-bili** [migueldeicaza/SwiftGodot#413]
Thanks for the greate library. I just have a question.
Can i use this libirary to embed Godot game to my existing native mobile application or react native ,flutter?

Thanks

**Comment by migueldeicaza** [comment]
Not really, this is a system to allow you to extend Godot games with Swift.

**Comment by ducpt-bili** [comment]
hi @migueldeicaza , do you have any solution or guide link for this? Android already support. Thanks.
