### ISSUE TITLE
[Windows] GodotSwift and SwiftSyntax libraries are being rebuilt every time

### ISSUE THREAD

**Issue by daniele-niero** [migueldeicaza/SwiftGodot#429]
I have encountered a problem where both GodotSwift and SwiftSyntax libraries are being rebuilt every time I compile my project. 
This makes it extremely hard to develop and test a game on Windows.

The project tested is the SimpleRunnerDriver from the Documentation.

I can understand a slow build the first time, but changing a bit the SimpleRunnerDriver.swift shouldn't trigger the recompilation of SwiftGodot (and by reflection SwiftSyntax)

Swift version: 5.9.2
Operating System: Windows 10
Godot version: 4.2

Is this  a known issue on Windows?

**Comment by migueldeicaza** [comment]
I didn’t know where to start, since I don’t even have a windows machine with me currently, but @tishin found and fixed the issue.

thank you for the report

**Comment by daniele-niero** [comment]
Thank to you guys for the prompt fix.

With Swift 5.9.2 I still had compilation problems and linking that took ages.
I also tried on a different machine and with a newly created project. The problem was still there.

But I just update Swift to 5.10 and now everything seems to work just fine (after the first compilation)

I thought it was worth to mention this.

Thanks again
