### ISSUE TITLE
What is the state of reverse engineering SwiftGodot?

### ISSUE THREAD

**Issue by Qws** [migueldeicaza/SwiftGodot#441]
Apparently it takes almost no effort to reverse engineer a Godot game relying on GDscript, but also a very little effort to reverse engineer a .NET Godot game.

I have interest in SwiftGodot, simply because I want to learn Swift and I think a game engine that doesn't use garbage collector is a very good thing. But I'm curious how reverse engineering state is with SwiftGodot? Is it harder or just as easy? Or does it depend on the platform?

**Comment by migueldeicaza** [comment]
Please do not use issues to discuss topics, move this topic to Discussions.
