### ISSUE TITLE
The example in "@onready annotation" in the docs produces errors

### ISSUE THREAD

**Issue by roydbt** [migueldeicaza/SwiftGodot#443]
The example:
```swift
class Demo: Node {
	var myLabel: Node3D


	override func _ready () {
		myLabel = getNode (path: "myLabel") as? Node3D
	}
}
```
produces the following errors:
1. The class "Demo" doesn't have initializers
2. Something about how "getNode (path: "myLabel") as? Node3D" produces "Node3D?" and not "Node3D" for myLabel

**Comment by migueldeicaza** [comment]
Thanks, the docs have been updated, for now do:

1. Add @Godot attribute to the class
2. Change the Node3D to "Node3D?"
