### ISSUE TITLE
Hot reloading doesn't work

### ISSUE THREAD

**Issue by roydbt** [migueldeicaza/SwiftGodot#449]
Whenever I build the Swift project, I must restart the Godot project for changes, such as new classes and new `@Callable` methods, to take effect.

**Comment by Nemesisprime** [comment]
Related to https://github.com/migueldeicaza/SwiftGodot/issues/433 

I've been kind of looking into it but haven't really had the time/focus yet.

**Comment by migueldeicaza** [comment]
This is a duplicate of the other issue.

**Comment by daniele-niero** [comment]
Hi,

I don't think this is working for Windows. Am I correct?

If I rebuild without closing Godot when I go back to it, it simply crashes
