### ISSUE TITLE
PackedInt32Array takes Int64s instead of Int32s

### ISSUE THREAD

**Issue by rktprof** [migueldeicaza/SwiftGodot#489]
**Describe the bug**
PackedInt32Array requires an Int64 for most of its functions like append(), has(), find(), fill() etc.

additionally the append() function requires the "value:" argument label which seems superfluous

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to append an Int32 to a PackedInt32Array
2. Compile, see error

**Expected behaviour**
I'd expect PackedInt32Array functions to take an Int32

**Additional context**
The issue is reflected in the docs: https://migueldeicaza.github.io/SwiftGodotDocs/documentation/swiftgodot/packedint32array/append(value:)/

**Comment by rktprof** [comment]
Seems to be the case with PackedFloat32Array as well as it only takes Doubles

**Comment by migueldeicaza** [comment]
While the data structures store the data in the lower format, the actual information transfer is done with the larger data types.

So I am hesitant to include an additional cast that duplicates work.

**Comment by rktprof** [comment]
I see, it just felt a bit redundant to have to cast my Int32 to an Int64 in order to store as an Int32, but I guess it's not that big of a deal since you're unlikely to be surprised by truncated Int64 when adding to an PackedInt32Array

**Comment by migueldeicaza** [comment]
Mhm, but the indexers already provide this convenience.   Perhaps I should add manually overloads for convenience.

**Comment by migueldeicaza** [comment]
Added conveniences
