### ISSUE TITLE
Putting a wrong name in @BindNode does not produce an error message

### ISSUE THREAD

**Issue by roydbt** [migueldeicaza/SwiftGodot#490]
When I misspell a `@BindNode` variable's name and run the program, it crashes and produces no error message at all in the Godot debugger.

**Comment by migueldeicaza** [comment]
The reason is that this uses a non-optional type, so it forces a cast, any errors are not logged.   There are other problems with BindNode that can not be fixed on Linux/Windows, so I recommend to use `@SceneTree` macro instead which is very similar, but produces an optional value
