### ISSUE TITLE
Support for utility functions

### ISSUE THREAD

**Issue by alicerunsonfedora** [migueldeicaza/SwiftGodot#50]
Godot provides a host of utility functions used in both GDScript and C# such as `abs`, `printerr`, and `preload`, which allow access to common functions. In C#, these methods are prefixed under the `GD` object.

The generator scripts support decoding these utility functions, but they don't appear to exist anywhere in the generated library. As a user/developer, I'd love to see these methods exposed, since they would allow me to perform actions such as:

- Preloading resources for textures when creating sprites
- Printing to Godot's console (Swift.print doesn't do anything in this regard)
- Use Godot's built-in random libraries (and other math functions) to achieve consistent results, regardless of language

**Comment by migueldeicaza** [comment]
Thanks for the feedback.

I initially did not bind them, as they looked like functions that were suitable for a smaller runtime and contained a lot of duplicate functionality from Swift, so your explanation of why this is needed is great.

Will get to it.

**Comment by alicerunsonfedora** [comment]
Glad I could be of help. I think it might make sense to have these utility functions in a structure like `Godot` or something similar, since I believe all of these util functions would be static anyway. The C# version of the Godot APIs stores them under `GD`, if I'm not mistaken.

**Comment by migueldeicaza** [comment]
Added the utility functions, although I have the impression many of those (like their Vector counterparts) are not probably best handled in Swift directly.
