### ISSUE TITLE
Unable to Create Swift GDExtension on Windows

### ISSUE THREAD

**Issue by atlasapplications** [migueldeicaza/SwiftGodot#508]
OS: Windows 11
Swift: 5.10.1

**Overview**
Using the documentation, I recreated the example project but with Windows and I'm unable to get a working GDExtension for Swift. Everything compiles correctly and the binaries are produced as expected but when I put them in the bin folder Godot produces an error that states "Can't open dynamic library:...." "Error 126: The specified module could not be found."

**Expected behavior**
There should be a Node that simply prints "Hello World from Swift."

**Minimal Reproduction Sample**
This project shows my code.
[swift_example.zip](https://github.com/user-attachments/files/16352031/swift_example.zip)

**Comment by bestwnh** [comment]
This info should add to the readme.

**Comment by migueldeicaza** [comment]
Which document were you reading?
