### ISSUE TITLE
Current XCFramework doesn't have targets for macOS-arm64

### ISSUE THREAD

**Issue by alicerunsonfedora** [migueldeicaza/SwiftGodot#51]
In the current tagged release of the library, the built XCFramework only offers support for the macOS x86-64 architecture. On Apple Silicon Macs, this framework is ignored when linking because of this issue.

**Comment by JustinSharkey** [comment]
Maybe related but I think I've run into the same/similar issue building exporting from Godot to Xcode/iOS. Logs say it can't find the classes but I don't have the logs atm and worry it might just be an issue with my configuration.

**Comment by migueldeicaza** [comment]
I published a new version and I am automating the process to release and update the docs at the same time
