### ISSUE TITLE
Discord instead of Slack?

### ISSUE THREAD

**Issue by mayoff** [migueldeicaza/SwiftGodot#526]
Just throwing this out there… I searched the Slack today (hoping there'd already some discussion of `~Copyable` types), found nothing, and was reminded by Slack that old messages are inaccessible.

Discord's unlimited message history would be nice to have.

Also the Godot project is on Discord.

**Comment by migueldeicaza** [comment]
There is a bridge on matrix which should give you access to the history:

https://github.com/migueldeicaza/SwiftGodot/discussions/350

I do not think we have discussed ~Copyable.

Generally, I think that long-term discussions would be better held here in the Discussions page or GitHub issues than Slack or Discord.

My general issue with Discord is that it feels like an assault on the senses, and while I am nominally on a bunch of Discords, I tend not to visit them often.   But happy if someone wants to setup a Slack to Discord bridge.

**Comment by mayoff** [comment]
Thanks. I was planning to open an issue to discuss `~Copyable` but wanted to do due diligence first.

**Comment by mayoff** [comment]
Also, since the compiler in Xcode 16.0 beta 4 and later crashes on a fairly simple use of an optional non-copyable type, I'm not going to bother starting that discussion yet.

https://github.com/swiftlang/swift/issues/75999
