### ISSUE TITLE
Request: Create an `@Export` property wrapper for exported variables

### ISSUE THREAD

**Issue by alicerunsonfedora** [migueldeicaza/SwiftGodot#57]
The current implementation for registering properties feels a little clunky. I'd love to see an implementation where one can use a property wrapper to have this work be done automatically:

```swift
class ExampleNode: Node {
	@Exported(type: .string, hint: .file, hintString: "*.json", usage: .propertyUsageDefault)
	var exampleFilePath: String = ""
}
```

It seems that, from this article, one should be able to access the property wrapper's enclosing structure/class to inject information to/from it: https://www.avanderlee.com/swift/property-wrappers/

**Comment by migueldeicaza** [comment]
I do not know how I would use this today, I think the upcoming macro support, plus some custom reflection could do it.

The challenges would be:

1. Would need to hook these up into a class initializer that I inject, or run first time the class is used (this I can detect)
2. Would need to be able to enumerate all properties with the attribute (this I do not think is possible today)
3. Would need to get the property type (this I also do not think is possible today)
4. Extract the metadata from the property wrapper (same)

There was a proposal for Swift reflection that was punted recently:

https://forums.swift.org/t/returned-for-revision-se-0385-custom-reflection-metadata/63758/2

I have some pointers for how to implement one manually, but it is a long road.

**Comment by migueldeicaza** [comment]
See also #26

**Comment by nvanfleet** [comment]
I think this would be a really good improvement. I tried yesterday to add a few properties and it takes a huge amount of work IMO and I still don't quite know what some of those fields require.

**Comment by alicerunsonfedora** [comment]
I'm currently looking into writing some helper methods that make registering properties in the editor a little clearer, such as making a picker, text field, etc.

I'm hoping that, with enough time and effort, I can come up with a SwiftUI-like solution for registration. But that'll be later down the line. If you'd like to look into those helper methods, feel free to look at my current fork at https://github.com/alicerunsonfedora/SwiftGodot. Once I'm happy with what I have, I'll make a PR to add this to the main codebase.

**Comment by nvanfleet** [comment]
@alicerunsonfedora I will look out for that, in the meantime, how can I just create a property for a single var that would be a node3D.

So I want the equivalent of 
```
@export
var focus_character: Node3D
```

I can't seem to find whatever combination of hint and type to get that to function

```
        let propertyName = "focus_character"
        let description: GString = "A character that is focussed on by the following terrain"
        let setProperty = StringName("set_\(propertyName)")
        let getProperty = StringName("get_\(propertyName)")
        let propertyType = Variant.GType.nodePath
        let propertyHint = PropertyHint.nodeType
        let property = PropInfo(propertyType: propertyType, propertyName: StringName(propertyName),
                                className: StringName("FollowingTerrain"), hint: propertyHint,
                                hintStr: description, usage: .propertyUsageDefault)
        classInfo.registerMethod(name: setProperty, flags: .default, returnValue: nil, arguments: [property],
                                 function: FollowingTerrain.setFocusCharacter)
        classInfo.registerMethod(name: getProperty, flags: .default, returnValue: property, arguments: [],
                                 function: FollowingTerrain.getFocusCharacter)
        classInfo.registerProperty(property, getter: getProperty, setter: setProperty)
```

**Comment by alicerunsonfedora** [comment]
I haven't done node paths yet, so I can't say for certain what that hint string would be. Maybe hit someone up in the Godot Discord to see if anyone knows?

https://discord.gg/g4sqqStAdc

**Comment by migueldeicaza** [comment]
Macros we're announced today!

**Comment by nvanfleet** [comment]
This would be really exciting if it could be easier. My current project just abandoned using any exports

**Comment by alicerunsonfedora** [comment]
> I'm currently looking into writing some helper methods that make registering properties in the editor a little clearer, such as making a picker, text field, etc.
> 
> I'm hoping that, with enough time and effort, I can come up with a SwiftUI-like solution for registration. But that'll be later down the line. If you'd like to look into those helper methods, feel free to look at my current fork at https://github.com/alicerunsonfedora/SwiftGodot. Once I'm happy with what I have, I'll make a PR to add this to the main codebase.

I've just made the PR for this: https://github.com/migueldeicaza/SwiftGodot/pull/89

**Comment by migueldeicaza** [comment]
Implemented
