### ISSUE TITLE
VariantCollection auto-unwrapping of Object-derived classes crashes

### ISSUE THREAD

**Issue by cbackas42** [migueldeicaza/SwiftGodot#590]
**Describe the bug**
When using a VariantCollection, accessing its contents via index crashes due to attempting to unwrap the variant automatically. I included the GArray in the example below just for comparison, because it works correctly.

The crash occurs here:
```swift
/// Accesses the element at the specified position.
    public subscript (index: Index) -> Element {
        get {
            let v = array [index]
            return Element(v)!
        }
        set {
            array [index] = Variant(newValue)
        }
    }
```
On the "return Element(v)!" line, producing these messages seen in LLDB:
Attempted to initialize a new `Resource` with <StyleBoxFlat#-9223372008752937711> but it is not possible to initialize a SwiftGodot.Object in a Swift initializer. Instead, use `Resource.makeOrUnwrap(variant)`.
SwiftGodot/VariantCollection.swift:58: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**To Reproduce**
Here is a trivial class to use to reproduce this:
```swift
@Godot
class TestContainers: Node3D, @unchecked Sendable
{
	override func _ready()
	{
		GD.print("GArray size: \(resAsGArray.count), VariantCollection size: \(resAsVar.count)")
		if resAsGArray.count > 0
		{
			GD.print(resAsGArray[0])
		}
		if resAsVar.count > 0
		{
			GD.print(resAsVar[0])
		}
	}

	@Export(.arrayType,"Resource") var resAsGArray: GArray = GArray()
	@Export(.arrayType,"Resource") var resAsVar: VariantCollection<Resource> = VariantCollection<Resource>()
}```

Add an instance of TestContainers to any scene, then in the editor assign any resource to each of its Arrays. In the Godot editor, this is done by:
1) Click "Add Element" on the arry
2) Click on the Pencil icon to the right of the new element and select "Object"
3) Drag any resource from your project into the slot



**Expected behavior**
The element is produced from the container as expected.


**Desktop (please complete the following information):**
 - OS: macOS 15.0.1
 - Swift 6
 - Godot 4.3

**Comment by IkkarionCross** [comment]
Looking at the current code in the repository. I this is already solved, here is the [PR 576](https://github.com/migueldeicaza/SwiftGodot/pull/576

**Comment by migueldeicaza** [comment]
Thank you, closing it.
