### ISSUE TITLE
Multi-argument signals only return their last value

### ISSUE THREAD

**Issue by alicerunsonfedora** [migueldeicaza/SwiftGodot#60]
There appears to be a bug with multi-argument signals where only the last argument is returned as the entire list.

**Steps to Reproduce**

1. Create a Swift class and add a signal into the class info:

```swift

class AClass: Node {
	static var recognizedSignalName = StringName("recognized")
    static var initClass: Void = {
        let classInfo = ClassInfo<AClass>(name: "\(AClass.self)")

        // MARK: Signal Registration
        let recognizedSignalProps = [
            PropInfo(propertyType: .string,
                     propertyName: StringName("gesture"),
                     className: StringName("\(AClass.self)"),
                     hint: .typeString,
                     hintStr: "The gesture pattern that was recognized.",
                     usage: .propertyUsageDefault),
            PropInfo(propertyType: .float,
                     propertyName: StringName("accuracy"),
                     className: StringName("\(AClass.self)"),
                     hint: .range,
                     hintStr: "The accuracy rating reported by Protractor.",
                     usage: .propertyUsageDefault)
        ]
        classInfo.registerSignal(name: recognizedSignalName, arguments: recognizedSignalProps)
}

```

2. In some function, invoke the signal emission:

```swift
emitSignal(signal: Self.recognizedSignalName, Variant(stringLiteral: "Hi there"), Variant(Float(0.18)))
```

3. Add the extension to Godot and create a Node2D with the Swift node as its child.
4. Write a custom script for this Node2D and attach it:

```gdscript
extends Node2D

@onready var a_class: AClass = $AClass

# Called when the node enters the scene tree for the first time.
func _ready():
	a_class.recognized.connect(_template_recognized)


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

func _template_recognized(name: String, accuracy: float):
	print("Name", name, "Accuracy", accuracy)
```

5. Run the game. Notice the following:

- Errors are reported where argument types are mismatched.
- Fixing the errors such as the following work, but they show the last value being duplicated:

```gdscript
func _template_recognized(name: float, accuracy: float):
```

**Comment by migueldeicaza** [comment]
Could you share the error messages?

Just from reading the code, I suspect the issue is in emitSignal and the code I generate for variants - but the visual inspection does not show any obvious culprits, I will need to dig deeper later.

**Comment by migueldeicaza** [comment]
WHOA!

I figured it out purely from the inspection.  Fixing.

**Comment by migueldeicaza** [comment]
Correction, no, I was wrong, that was not it.

**Comment by migueldeicaza** [comment]
I was wrong about being wrong, but for the wrong reason.

The issue is that I generate this code for var-args:

```
        var _result: Variant.ContentType = Variant.zero
        var copy_signal = Variant (signal)
        var args: [UnsafeRawPointer?] = [
            UnsafeRawPointer(&copy_signal.content),]
        var varArgCopies: [Variant] = []
        for varg in arguments {
            let copy = Variant (varg)
            varArgCopies.append (copy)
            args.append (&copy.content)
        }
```

The idea being that args contains the pointers to the individual arguments.   And I had assumed that the call to `let copy = Variant` would allocate a new object in the heap, but it seems to be returning the same address every time, which is why I end up replicating the argument.  Because copy always gets the same address.

I was assuming that reference classes (in this case Variant) would be heap allocated, and the call to append would just copy the reference, and I would get a new heap allocated value in the next iteration, but it does not look that way.

I am both a little puzzled by why this is happening, and a little puzzled as to how to proceed.  Mulling over.

**Comment by migueldeicaza** [comment]
Fixed, it took me a while, because the Swift optimizer seems to be too smart for its own good.
