### ISSUE TITLE
Update README to reflect newly added 4.3 support

### ISSUE THREAD

**Issue by DandyLyons** [migueldeicaza/SwiftGodot#605]
README says: 

>SwiftGodot provides Swift language bindings for the Godot 4.2 game engine using the new [GDExtension](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/what_is_gdextension.html) system (for 4.1 compatibility, use the 4.1 branch, preview for upcoming 4.3 release is in the 4.3 branch).

If I understand correctly, this is no longer accurate since 4.3 support was added in release 0.45.0 

We should update the README to show that it is no longer required to switch to the 4.3 branch.

**Comment by migueldeicaza** [comment]
Good observation!  Fixed.
