### ISSUE TITLE
import Swift code into Godot project (opposite thing)

### ISSUE THREAD

**Issue by Gargo** [migueldeicaza/SwiftGodot#61]
Is it possible to embed a native iOS project into iOS Godot project

**Comment by migueldeicaza** [comment]
Use SwiftGodotKit, the companion module

**Comment by Gargo** [comment]
@migueldeicaza from its readme:
```
SwiftGodotKit provides a way of embedding Godot into an existing Swift application and driving Godot from Swift, without having to use an extension.
```
But I need vice versa to embed that Swift application into Godot Xcode project

**Comment by migueldeicaza** [comment]
Ah then this is the module you want.
