### ISSUE TITLE
Better coverage for GodotVariant

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#62]
It looks like to get a ShaderGlobal you can extract it and get a Variant. However this depends on what you are accessing to implement `GodotVariant`.  For me I am interested in accessing a Sampler2D which I assume is ultimately the `.object` type? It doesn't have coverage so it appears as if I can't ultimately access the object.

(I updated this because I think I was searching a checked out version of SwiftGodot that was missing some implementations for Vector etc).

**Comment by migueldeicaza** [comment]
Hello,

Could you show me a code snippet of what you are trying to do?   I could not follow along.

**Comment by nvanfleet** [comment]
Sure thing.

Firstly you need a Shader global that is Sampler2D with an image (Currently that is the only functional sampler2D in Godot 4). 

Then you try to access that sampler2D object like so 

```
// Get the shader setting that should (?) contain a Sampler2D
let shaderSetting = ProjectSettings().getSetting(name: "shader_globals/heightmap", defaultValue: Variant(-1))
```
But from there I don't know how to turn that returned variant into something that I can use. 

An example for a float shader global would look like this 
```
// Get the value from global shaders
let shaderSetting: Variant = ProjectSettings().getSetting(name: "shader_globals/heightmap", defaultValue: Variant(-1))
// Access the value by turning it into a float
let value: Float = Float(shaderSetting)
```

1. I'm not sure what type a Sampler2D should be, but I assume it's under object in GType or is a separate new type that doesn't exist in SwiftGodot (?). Sampler2D does exist in some RenderingDevice enum but it doesn't seem to interface into GodotVariant. 
2. I feel like defaultValue should be optional here, `getSetting` can also return an optional IMO.

So possibly
1. There needs to be a new GType for Sampler2D
2. There might need to be a Sampler2D class that can be used to access Sampler2D data (?) that would be a GodotVariant so it can be accessed

**Comment by migueldeicaza** [comment]
Thank you for the example!

I think I understand what you are trying to do.

I added a method to Variant: `asObject<T> () -> T?`

You should be able to call it like this:

```
let settingResult = ProjectSettings.getSetting (....)
var mySampler: Sampler2D? = settingResult.asObject
```

Let me know if it works.

**Comment by nvanfleet** [comment]
Is there a Sampler2D class in SwiftGodot? I can't seem to find it.
