### ISSUE TITLE
Unexpected non-optional

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#63]
I noticed that there are some variables in SwiftGodot which are shown as non optional.

For example GeometryInstance3D.materialOverride. In Godot this is generally nil unless you assign it but it appears as if SwiftGodot assumes it's populated? In the code of GeometryInstance3D it appears to be force unwrapping it instead of just making it an optional value. I kind of think this might crash if you ever check it when there is no value present.

There are numerous things that are optional in Godot and don't have an default value and should just be nil.

This also works for `MeshInstance3D. getSurfaceOverrideMaterial()` or even `MeshInstance3D.mesh`

**Comment by migueldeicaza** [comment]
Agreed, this information is sadly not present in Godot.  I suspect the only correct thing to do today is to flag both returns and parameters as optional and slowly introduce an annotation system to flag their nullability

**Comment by migueldeicaza** [comment]
this is not a new problem, sadly:

https://github.com/godotengine/godot-proposals/issues/2241

**Comment by migueldeicaza** [comment]
As I ponder this challenge, I think that it would be relatively innocuous to make all arguments optional, from an API usability, it might not be bad, but we would get some exceptions at runtime - just like C# or GDScript would.

The return values are a bit more complicated, there are some 545 of those spread across functions and properties.

The properties we might be able to write a script to instantiate every object type in Godot, and attempt to set/read the value to null, and those that abort, we can safely flag as non-Optional, the rest we flag as Optional.

Maybe a script to track every constructor that initializes 'Ref' fields beyond the default might be useful to determine if nulls are allowed or not.

**Comment by migueldeicaza** [comment]
Update, I did some measurements:

- We have some 114 properties that would need to be audited
- 432 method returns that would need to be audited

**Comment by migueldeicaza** [comment]
Ok, I have settled on a plan.

The baseline is that all parameters that are object references can be optional, this matches the C# behavior, and will produce runtime errors as opposed to compile time errors for those cases.

The same applies for return values.

That said, I now have a list of custom return values and parameters that can be manually be extended to flag "This return type is never nil" or "this parameter can never be nil" that we can grow over time.

The bad news is that this will likely produce some churn on the code that relies on this, but it is also the right thing to do.

**Comment by nvanfleet** [comment]
Neat thanks very much.
