### ISSUE TITLE
Default function values?

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#66]
I noticed that there are default parameters provided in the APIs. 

For example 

`void add_surface_from_arrays ( PrimitiveType primitive, Array arrays, Array[] blend_shapes=[], Dictionary lods={}, ArrayFormat flags=0 )` [from](https://docs.godotengine.org/en/stable/classes/class_arraymesh.html#class-arraymesh-method-add-surface-from-arrays)

Is it possible to provide this in SwiftGodot? The example above usually just has `add_surface_from_arrays(.primitiveTrianges, data)` and most normal use of it have only those in use

I also noticed that the last value which is `0` and is from Mesh.ArrayType is a enum that doesn't have a case for `0` so it seems like a valid case but not defined in Godot. So maybe SwiftGodot needs an autogenerated `.none = 0` value for generated enums

**Comment by alicerunsonfedora** [comment]
It should be possible, I believe, since the extension API JSON file includes default values for arguments in function signatures.

**Comment by migueldeicaza** [comment]
Support for this exists, but is lacking a handful of cases, they are detailed here:

https://github.com/migueldeicaza/SwiftGodot/issues/7

**Comment by migueldeicaza** [comment]
Ok, one small update:

`Mesh.Arraytype` is an `OptionFlag` which is slightly different than an enum, it allows multiple values to be combined together.    The equivalent to 0 would be just the empty set, so you would provide it like this: `[]`

**Comment by migueldeicaza** [comment]
These particular cases are handled, and I have updated #7 with the pending cases.

**Comment by nvanfleet** [comment]
Awesome thank you very much!
