### ISSUE TITLE
Unable to build for iOS with pre-built binary

### ISSUE THREAD

**Issue by alicerunsonfedora** [migueldeicaza/SwiftGodot#71]
It seems that a Swift package built for iOS is unable to detect SwiftGodot when loading from an xcframework.

**Steps to reproduce**  
1. Download a copy of the SwiftGodot.xcframework (or build it manually).
2. Create a Swift package with a Package.swift similar to below:

```swift
// swift-tools-version: 5.7

import PackageDescription

let package = Package(
    name: "AnthroBase",
    platforms: [.macOS(.v13), .iOS(.v16)],
    products: [
        .library(
            name: "ExtensionName",
            type: .dynamic,
            targets: ["ExtensionName"]),
    ],
    targets: [
        .target(
            name: "ExtensionName",
            dependencies: ["SwiftGodot"],
            swiftSettings: [.unsafeFlags(["-suppress-warnings"])],
            linkerSettings: [.unsafeFlags(["-Xlinker", "-undefined","-Xlinker", "dynamic_lookup"])]),
        .binaryTarget(name: "SwiftGodot", path: "../SwiftGodot.xcframework")
    ]
)
```

3. Create the extension as you normally would (see README).
4. Try to run the following in the terminal (this also works in Xcode):

```bash
xcodebuild -scheme "ExtensionName" -destination 'generic/platform=iOS' \
	-derivedDataPath xcbuild -skipPackagePluginValidation \
	-configuration Release
```
5. Notice that the build fails for iOS devices.

**Expected behavior**  
The iOS version can locate from the xcframework and build accordingly.

**Comment by migueldeicaza** [comment]
Mhm, I am not able to reproduce this

My plain package that builds with the above xcodebulid command, unpack and run `make`

[testa.tar.gz](https://github.com/migueldeicaza/SwiftGodot/files/11594273/testa.tar.gz)

**Comment by migueldeicaza** [comment]
Nice, I have fixed the script and the binaries.   It should work now.
