### ISSUE TITLE
A crash occurs when calling a Godot object's get method

### ISSUE THREAD

**Issue by alicerunsonfedora** [migueldeicaza/SwiftGodot#73]
Godot will crash when calling the `Object.get(property:)` method in an extension. I suspect it might be a memory-related issue, but not particularly helpful when trying to perform operations such as grabbing the playback machine in an animation tree:

```swift
public override func _ready() {
      sprite = getNodeOrNull(path: NodePath(stringLiteral: "Sprite")) as? Sprite2D
      animationTree = getNodeOrNull(path: NodePath(stringLiteral: "Sprite/AnimationTree")) as? AnimationTree
      animationPlayer = getNodeOrNull(path: NodePath(stringLiteral: "Sprite/AnimationPlayer")) as? AnimationPlayer
      // FIXME: This causes a crash. Why?
      animationState = animationTree?.get(property: StringName("parameters/playback")) as? AnimationNodeStateMachinePlayback
}
```

**Steps to reproduce**  
1. Clone https://github.com/Indexing-Your-Heart/game/tree/346a0a31fed0dfed4c60c1cdd0505b6b8a7e38b8 and follow the instructions to build the game.
2. Run `just edit-game` or open the project in the editor.
3. Open and run either `demos/environment_demo.tscn` or `areas/proto_st1.tscn`.
4. Notice that the game runs without any particular issues.
5. Uncomment line 47 in `AnthroBase/Sources/AnthroBase/AnthroCharacterBody2D.swift` and run `just build-all-deps`.
6. Repeat steps 2-3. Notice that the game crashes in the `_ready` method from the `get(property:)` method.

**Expected behavior**  
The `get` method returns a value that can be typecast accordingly. In the case of the reproduction steps, an `AnimationNodeStateMachinePlayback?`.

**Comment by migueldeicaza** [comment]
Thank you, the issue was a bug in the Variant return code marshaling.

The fix is on git.

That said, the code as it is being used won't work.   The return value of get(property:) is a Variant, what you want to do is call `asObject<AnimationNodeStateMachinePlayback>`

**Comment by alicerunsonfedora** [comment]
> The fix is on git.

Would you be able to point to which commit contains the fix in question? I can't seem to find it.

**Comment by migueldeicaza** [comment]
Apologies I forgot to push;  it should be up jiw
