### ISSUE TITLE
Bad linkage for input?

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#77]
I have a node that is taking in input which definitely exists but I end up getting errors from Godot that they don't exist.

<img width="820" alt="Screenshot 2023-05-30 at 7 59 23 AM" src="https://github.com/migueldeicaza/SwiftGodot/assets/1486399/063f17f8-9593-49c3-bfcc-31532809fcbb">

Basically just
```
        var movementInputVector = Input.shared.getVector(negativeX: "move_left", positiveX: "move_right",
                                                         negativeY: "move_forward", positiveY: "move_back")
```

**Comment by alicerunsonfedora** [comment]
That’s really weird, since I have similar stuff and it’s working completely fine for me…

See: https://github.com/Indexing-Your-Heart/game/blob/9af7767d09c0b3bac94a5aa730efa6b480ec4bfb/AnthroBase/Sources/AnthroBase/AnthroCharacterBody2D.swift#L37

**Comment by nvanfleet** [comment]
@alicerunsonfedora  you have custom inputs or you use the standard ones "ui_text_..."?

**Comment by alicerunsonfedora** [comment]
I have both.

**Comment by nvanfleet** [comment]
@alicerunsonfedora hmm well I am definitely not sure what's up. The project definitely has it. Maybe @migueldeicaza has an idea

**Comment by migueldeicaza** [comment]
I am not familiar with this input system, I am sorry :-(

**Comment by nvanfleet** [comment]
@migueldeicaza okay I thought this was possibly related to something about how SwiftGodot works with inputs since this is working in my GDscript version of the same class. But maybe it's something separate

**Comment by nvanfleet** [comment]
Okay so I made a test project
```
        GD.print("Checking")
        let input = Input.shared.getVector(negativeX: "move_left", positiveX: "move_right",
                                           negativeY: "move_forward", positiveY: "move_back")
        GD.print("Input \(input)")
        let action = Input.shared.getActionRawStrength(action: "jump")
        GD.print("Action \(action)")
        let action2 = Input.shared.getActionStrength(action: "jump")
        GD.print("Action 2 \(action2)")
```

The output I get is 
```
Checking
  The InputMap action "move_right" doesn't exist. Did you mean "ui_right"?
  The InputMap action "move_left" doesn't exist. Did you mean "ui_left"?
  The InputMap action "move_back" doesn't exist. Did you mean "ui_text_backspace"?
  The InputMap action "move_forward" doesn't exist.
  The InputMap action "move_right" doesn't exist. Did you mean "ui_right"?
  The InputMap action "move_left" doesn't exist. Did you mean "ui_left"?
  The InputMap action "move_back" doesn't exist. Did you mean "ui_text_backspace"?
  The InputMap action "move_forward" doesn't exist.
Input Vector2(x: 0.0, y: 0.0)
  The InputMap action "jump" doesn't exist.
Action 0.0
  The InputMap action "jump" doesn't exist.
Action 2 0.0
```

[TestSwiftGodot.zip](https://github.com/migueldeicaza/SwiftGodot/files/11644854/TestSwiftGodot.zip)

**Comment by alicerunsonfedora** [comment]
Looks like the ZIP is empty?

![Screenshot of unzipped TestSwiftGodot file](https://github.com/migueldeicaza/SwiftGodot/assets/13445064/a1b1390a-d417-44f0-b3d7-f169d6f5c309)

In any case, check if the actions are defined in your project.godot file. It could be possible that the changes simply aren't getting written.

For example, this is what mine looks like:

```ini
[input]

move_up={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":119,"echo":false,"script":null)
]
}
move_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":97,"echo":false,"script":null)
]
}
move_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":100,"echo":false,"script":null)
]
}
move_down={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":83,"key_label":0,"unicode":115,"echo":false,"script":null)
]
}
interact={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":69,"key_label":0,"unicode":101,"echo":false,"script":null)
]
}
cancel={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194305,"key_label":0,"unicode":0,"echo":false,"script":null)
]
}
timeline_next={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":32,"key_label":0,"unicode":32,"echo":false,"script":null)
]
}
```

**Comment by nvanfleet** [comment]
Hey @alicerunsonfedora  sorry I was having problems with my computer and didn't realize that the compressing failed. It's here
[TestSwiftGodot.zip](https://github.com/migueldeicaza/SwiftGodot/files/11646715/TestSwiftGodot.zip)

It's definitely saving the settings as I showed in the original screenshot of the Godot UI and can see from the Godot project file. These settings worked in my GDScript as well it only happens with the Swift code somehow.


<img width="207" alt="Screenshot 2023-06-04 at 2 32 30 PM" src="https://github.com/migueldeicaza/SwiftGodot/assets/1486399/388dc149-b163-4c0b-b59d-9bc75d2dd801">

**Comment by alicerunsonfedora** [comment]
Looks like your build scripts might not be working correctly, hence the errors being seen...

![image](https://github.com/migueldeicaza/SwiftGodot/assets/13445064/6e9956ad-8ce6-4d4d-b94e-7200bd6fff4a)

**Comment by nvanfleet** [comment]
> Looks like your build scripts might not be working correctly, hence the errors being seen...
> 
> ![image](https://user-images.githubusercontent.com/13445064/243214031-6e9956ad-8ce6-4d4d-b94e-7200bd6fff4a.png)

I didn't include any compiled data, I can verify that it's not due to things not compiling

**Comment by nvanfleet** [comment]
Actually that specific error is just because Godot looks into the build directory and things things like SimpleExtension which is in the SwiftGodot source should be part of the project. You can resolve this by putting `.gdignore` in the build directory so Godot doesn't look in there. I had wiped a bunch of compilation folders so I could reduce the size of the binary. But trust me I was not getting those errors and they aren't contributing anything

**Comment by alicerunsonfedora** [comment]
I'm not enturely sure what the problem is, then. As far as I can tell, I'm not receiving these sorts of issues in my current project utilizing SwiftGodot, so I can't reliably reproduce the issue.

**Comment by nvanfleet** [comment]
> I'm not entirely sure what the problem is, then. As far as I can tell, I'm not receiving these sorts of issues in my current project utilizing SwiftGodot, so I can't reliably reproduce the issue.

Okay, I don't get it, interesting that you are seeing the same issues on my project at least.

**Comment by nvanfleet** [comment]
Looks like this is a known issue https://github.com/godotengine/godot/issues/74993

**Comment by alicerunsonfedora** [comment]
> Closing this, it was just that you can't check for input within the editor for gdextensions

Facepalm moment, it didn't occur to me that it was trying to check the inputs in-editor (I thought you were having issues in-game). This makes a lot of sense now...

**Comment by nvanfleet** [comment]
@alicerunsonfedora yeah, it was a particular gdextension thing, but it's kind of funny to get used to everything being a @tool
