### ISSUE TITLE
App launch crash when accessing Dictionary values?

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#80]
```
        let imageVariant = ProjectSettings.shared.getSetting(name: "shader_globals/heightmap", defaultValue: Variant(-1))
        GD.print("Found this value IMAGE: \(imageVariant.gtype) variant: \(imageVariant) desc: \(imageVariant.description)")
        
        let dict2: Dictionary? = SwiftGodot.Dictionary(imageVariant)
        GD.print("dictionary2: \(dict2) \(dict2?["type"]) \(dict2?["value"])")
        
// part b
        if let result = dict2?.get(key: Variant("type"), default: Variant(-1)) {
            let value = String(result)
            GD.print("2 Found this value \(value)")
        }
```

I am having trouble accessing a SwiftGodot.Dictionary value using the subscript. For example the log up to part B is

```
Found this value IMAGE: dictionary variant: SwiftGodot.Variant desc: { "type": "sampler2D", "value": "res://heightmap.png" }
dictionary2: Optional(SwiftGodot.Dictionary) nil nil
```

So we can see in the description that it has type and value but it just returns nil.

If part B however is part of the project it just crashes the app on launch automatically somehow. I can't see what the error is however as it doesn't show it anywhere.

Attached is a sample project which has the aforementioned code

[TestSwiftGodot.zip](https://github.com/migueldeicaza/SwiftGodot/files/11644831/TestSwiftGodot.zip)

**Comment by nvanfleet** [comment]
@migueldeicaza not sure if you saw this

**Comment by migueldeicaza** [comment]
Thanks for the reminder, fixed.

Variant marshaling got broken at some point when I moved from structs to classes, and forgot to remove the internal mapping that declared it as a struct.
