### ISSUE TITLE
Updating array values or possibly accessing array values is broken

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#90]
I had a simple script that did the following
1. Take a plane mesh
2. Iterate through its faces and put them into a ConcavePolygonShape3D (though change the Y value based on a height map).

When migrating to SwiftGodot that is now broken.

<img width="842" alt="Screenshot 2023-06-08 at 9 38 24 PM" src="https://github.com/migueldeicaza/SwiftGodot/assets/1486399/aee76ab4-3215-4da6-b6bf-6c0479e4cb96">

This is the unmodified planemesh

<img width="688" alt="Screenshot 2023-06-08 at 9 37 41 PM" src="https://github.com/migueldeicaza/SwiftGodot/assets/1486399/47489a45-5f4e-42d5-9dea-d5476eeec864">

This is what the planemesh looks like if all you do is iterate through the vertices of the PlaneMesh and set the value to the same index. 

```
        let planeVerticies = self.planeMesh.getFaces().duplicate()
        for i in 0..<planeVerticies.size() {
            let value = planeVerticies[Int(i)]
            
            // a: Try using this code here, it will mangle the plane mesh (notice I have to convert from int64 since size returns int64 but the subscript uses Int. 
//            planeVerticies[Int(i)] = value
            
            // b: Try using this one instead, it also mangles the mesh. This function uses Int64
            planeVerticies.set(index: i, value: value)
        }
        
        // If a or b are uncommented this will break the plane mesh
        (self.collisionShape?.shape as? ConcavePolygonShape3D)?.data = planeVerticies
```

Notice that in no way is the vertex even being edited here. It's iterating through all the vertices accessing at `i` and then setting right back to `i` again. But if you run the code (See attached) and have both a & b commented out it will show up fine. But just setting it back to itself breaks it. 

It seems like either accessing the vertex or setting it must somehow mangle the data. 

The weird part is that it looks like the y values of the vertices end up in the wrong place too. If it was just changing the organization of the vertices I feel like it would not have vertices that were higher than zero 🤔 So maybe it's just that Vector3 is getting mangled in some kind of direction going in or out of Godot.

[TestSwiftGodot.zip](https://github.com/migueldeicaza/SwiftGodot/files/11702439/TestSwiftGodot.zip)

**Comment by migueldeicaza** [comment]
Quick question: was this a recent regression?

**Comment by migueldeicaza** [comment]
This is very strange: I single stepped one case that was getting the wrong data, and the C++ code gets both the right index, with the right value, but immediately upon return the value is wrong.

Still looking into it.

**Comment by migueldeicaza** [comment]
Ouch, this was a copy/paste error.

The fix:
```
 extension PackedVector3Array {
     public subscript (index: Int) -> Vector3 {
         get {
-            let ptr = gi.packed_vector2_array_operator_index (&content, Int64(index))
+            let ptr = gi.packed_vector3_array_operator_index (&content, Int64(index))
             return ptr!.assumingMemoryBound(to: Vector3.self).pointee
         }
```

**Comment by nvanfleet** [comment]
ah! awesome thanks. I had looked at the code and didn't see that.

**Comment by migueldeicaza** [comment]
No problem, it is my fault, I appreciate your bug reports, they are incredible, and help advance the binding.
