### ISSUE TITLE
SwiftGodot.Dictionary access seems broken

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#91]
Creating a simple dictionary and trying to poke the values appears to be broken.

1. Create a SwiftGodot.Dictionary
2. Set a value
3. Try to access the value

results:
- There is an error in the log from Godot and the value returned is nil, this happens if you are trying to access a value that exists or does not

```
    private func testDictionary() {
        let dict = SwiftGodot.Dictionary()
        dict["test"] = Variant(GString("expected value"))
        GD.print("\(dict["test"])")
        GD.print("\(dict["missing_value"])")
    }
```

```
  core/variant/variant_op.cpp:1024 - Index type_a = 41549472 is out of bounds (Variant::VARIANT_MAX = 38).
nil
  core/variant/variant_op.cpp:1024 - Index type_a = 41549472 is out of bounds (Variant::VARIANT_MAX = 38).
nil
```

[TestSwiftGodot.zip](https://github.com/migueldeicaza/SwiftGodot/files/11708631/TestSwiftGodot.zip)

**Comment by migueldeicaza** [comment]
Thank you for this report, this was an indexer binding bug.

It should be fixed now, I validated this works
