### ISSUE TITLE
Lerping appears to return unexpected results

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#92]
```
        let resultVariant = GD.lerp(from: Variant(Float(100)), to: Variant(Float(75)), weight: Variant(Float(0.5)))
        let attempt1 = Float(resultVariant)
        let attempt2 = Float(resultVariant)
        GD.print("attempt1 \(attempt1) attempt2 \(attempt2)")
        
        let resultVariant1 = GD.lerp(from: Variant(Float(100)), to: Variant(Float(1000)), weight: Variant(Float(0.5)))
        let attempt3 = Float(resultVariant1)
        let attempt4 = Float(resultVariant1)
        GD.print("(attempt3) \(attempt3) attempt4 \(attempt4)")
```

The above code just produces 

```
attempt1 Optional(0.0) attempt2 Optional(0.0)
(attempt3) Optional(0.0) attempt4 Optional(0.0)
```

1. It is a bit funny to be forced to use Variant for this function. I'm not sure if that's just to allow for type mixing? 
2. Double doesn't implement GodotVariant, so you can't really mix types in it anyway, and presumably can only do floats, and maybe Ints I guess if you can lerp that (?).
3. The output is not correct, it's not even always zeros, when I put real data into it it will pretty quickly spit out a nan

**Comment by migueldeicaza** [comment]
It does lerp on vectors and colors for instance.

**Comment by migueldeicaza** [comment]
Fixed, another double/float mismatch, apologies!
